services:
  traefik:
    image: traefik:2.11
    environment:
      - "INFOMANIAK_ACCESS_TOKEN=TOKEN_CHANGE_ME"
    container_name: traefik
    networks:
      - wis2bridge
    restart: unless-stopped
    ports:
      - 8883:8883
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/rocky/wis2-data-generator/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - /home/rocky/wis2-data-generator/traefik/dynamic:/etc/traefik/dynamic:ro
      - /home/rocky/wis2-data-generator/traefik/acme.json:/acme.json
    labels:
      traefik.enable: true
      traefik.http.routers.traefik.entrypoints: websecure
      traefik.http.routers.traefik.rule: PathPrefix(`/dashboard`)
      traefik.http.routers.traefik.tls: true
      traefik.http.routers.traefik.tls.certresolver: letsencrypt
      traefik.http.routers.traefik.tls.domains[0].main: HOSTNAME_CHANGE_ME
      traefik.http.routers.traefik.service: api@internal
networks:
  wis2bridge:
    external: true
