== Terms and definitions

This document uses the terms defined in https://portal.ogc.org/public_ogc/directives/directives.php[OGC Policy Directive 49], which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word “shall” (not “must”) is the verb form used to indicate a requirement to be strictly followed to conform to this Standard and OGC documents do not use the equivalent phrases in the ISO/IEC Directives, Part 2.

This document also uses terms defined in the OGC Standard for Modular specifications (https://portal.opengeospatial.org/files/?artifact_id=34762[OGC 08-131r3]), also known as the 'ModSpec'. The definitions of terms such as standard, specification, requirement, and conformance test are provided in the ModSpec.

=== Abbreviated terms

API:: Application Programming Interface
GB:: Global Broker
GC:: Global Cache
GDC:: Global Discovery Catalogue
GISC:: Global Information System Centre
GM: Global Monitor
HTTP:: Hypertext Transfer Protocol
HTTPS:: Hypertext Transfer Protocol Secure
JSON:: JavaScript Object Notation
OGC:: Open Geospatial Consortium
MQTT:: Message Queuing Telemetry Transport
WCMP2:: WMO Core Metadata Profile 2
WIS:: WMO Information System
WMO:: World Meteorological Organization
WNM:: WIS2 Notification Message
WTH:: WIS2 Topic Hierarchy
