[[global-discovery-catalogue-testing]]

=== Global Discovery Catalogue Service testing

==== Preparations for the test

- backup metadata repository
- metrics can be backed up, but as they are also rebuilt after a service restart, no backup is necessary here
- the GDC broker shall be made accesible to to the WIS2 test Global Broker, with access via the credentials `everyone-dev/everyone-dev` for the purpose of testing

==== Entering the test environment

The GDC implementation under test (IUT) is required to enter the test environment with the following state:

- empty metadata repository (0 records)
- empty / non-existent metadata archive zipfile

==== Test setup

The GDC test setup consists of the following:

* A test data bundle to consist of:
** 6 valid WCMP2 records
** 4 broken JSON WCMP2 records
** 1 invalid WCMP2 record
** 20 WNM documents, each of which pointing to the related WCMP2 records
** 1 WNM document specifying a WCMP2 record deletion
* all WCMP2 records stored on an HTTP server (GitHub)
** documents available at the following location: https://github.com/wmo-im/wis2-global-services-testing/tree/main/tests/global_discovery_catalogue/metadata
** all WNM documents updated to point to the correct HTTP server for proper HTTP dereferencing (raw GitHub) (example: https://raw.githubusercontent.com/wmo-im/wis2-global-services-testing/gdc-tests-update/tests/global_discovery_catalogue/metadata/valid/urn--wmo--md--io-wis2dev-11-test--climate.climate-daily.json)
* updating environment variables in `tests/default.env` as follows:
** `GDC_API`: URL to GDC API (including collection name)
** `GDC_CENTRE_ID`: the centre identifier of the GDC implementation under test (IUT)

Note that you can store secret environments in `tests/secrets.env` and refer to them in `tests/default.env` accordingly.

Given the GDC performs various checks on the centre identifier as part of the incoming topic from the Global Broker as well as the the WCMP2 identrifier check, GDC tests require a fixed WIS2 Node centre id.

The fixed WIS2 Node centre used for GDC tests is `io-wis2dev-11-test`.

==== Functional tests

===== Global Broker connection and subscription

====== Purpose

A Global Discovery Catalogue must connect to a Global Broker using the MQTT protocol with TLS and username/password authentication (everyone/everyone) and subscribe to the following topic:

* ``++cache/a/wis2/+/metadata/#++``

====== Steps

. Initialize the MQTT client with the necessary parameters such as the MQTT protocol version 5, TLS security, and username/password for authentication
. Connect the MQTT client to the Global Broker
. Once the connection is successful, attempt to subscribe to the following topics:
   - ``++cache/a/wis2/+/metadata/#++``
. Check if the subscription is successful. If the subscription is successful, proceed. If the subscription is not successful, the test fails
. Close the connections to the broker after the test

On successful completion, the following metrics should be modified:

* `wmo_wis2_gdc_connected_flag` for the centre-id from which the Global Discovery Catalogue connected to should be set to 1 (one)

===== Notification and metadata processing (success)

====== Purpose

The Global Discovery Catalogue should be able to process valid WCMP2 metadata record of core data published by a WIS2 Node.

====== Steps

. Initialize the MQTT client with the necessary parameters such as the MQTT protocol version 5, TLS security, and username/password for authentication.
. Connect the MQTT client to the Global Broker
. Once the connection is successful, attempt to subscribe to the following topics:
   - ``++cache/a/wis2/+/metadata/#++``
. Check if the subscription is successful. If the subscription is successful, proceed. If the subscription is not successful, the test fails
. On an incoming message:
.. find the canonical link object in the `links` array
.. from the matching link, issue a HTTP GET request against the matching `href` value
.. parse the HTTP response:
... validate against the WCMP2 Executable Test Suite (ETS)
... publish the WCMP2 record to the catalogue
... publish an ETS validation report as a notification message to the GDC MQTT broker
.. using the WCMP2 identifier (i.e. `$WCMP2_ID`), construct a path to the record on the GDC (`\https://HOST/collections/wis2-discovery-metadata/$WCMP2_ID`)

On successful completion:

* the resulting WCMP2 record should be available on the GDC API and contain an MQTT link / channel (using `cache/a/wis2`) foreach Global Broker
* the following metrics should be modified:
** `wmo_wis2_gdc_passed_total` for the centre-id from where the metadata was published from should be incremented by 1 (one)
** `wmo_wis2_gdc_core_total` for the centre-id from where the metadata (core data policy) was published from should be incremented by 1 (one)
* a notification message should arrive from the Global Broker under `monitor/a/wis2/CENTRE_ID_global-discovery-catalogue/centre-id`)

===== Notification and metadata processing (failure; record not found)

====== Purpose

The Global Discovery Catalogue should be able to process failing (record not found) WCMP2 metadata published by a WIS2 Node.

====== Steps

. Initialize the MQTT client with the necessary parameters such as the MQTT protocol version 5, TLS security, and username/password for authentication
. Connect the MQTT client to the Global Broker
. Once the connection is successful, attempt to subscribe to the following topics:
   - ``++cache/a/wis2/+/metadata/#++``
. Check if the subscription is successful. If the subscription is successful, proceed. If the subscription is not successful, the test fails
. On an incoming message:
.. find the canonical link object in the `links` array
.. from the matching link, issue a HTTP GET request against the matching `href` value
.. if the response is an HTTP status code of 404:
... publish an ETS error report as a notification message to the GDC MQTT broker

On successful completion:

* the following metrics should be modified:
** `wmo_wis2_gdc_failed_total` for the centre-id from where the metadata was published from should be incremented by 1 (one)
* a notification message should arrive from the Global Broker under `monitor/a/wis2/CENTRE_ID_global-discovery-catalogue/centre-id`)

===== Notification and metadata processing (failure; malformed JSON or invalid WCMP2)

====== Purpose

The Global Discovery Catalogue should be able to process failing (malformed JSON) WCMP2 metadata published by a WIS2 Node.

====== Steps

. Initialize the MQTT client with the necessary parameters such as the MQTT protocol version 5, TLS security, and username/password for authentication
. Connect the MQTT client to the Global Broker.
. Once the connection is successful, attempt to subscribe to the following topics:
   - ``++cache/a/wis2/+/metadata/#++``
. Check if the subscription is successful. If the subscription is successful, proceed. If the subscription is not successful, the test fails
. On an incoming message:
.. find the canonical link object in the `links` array.
.. from the matching link, issue a HTTP GET request against the matching `href` value.
.. parse the HTTP response:
.. if the JSON is malformed, or the WCMP2 is invalid:
... publish an ETS error report as a notification message to the GDC MQTT broker.

On successful completion:

* the following metrics should be modified:
** `wmo_wis2_gdc_failed_total` for the centre-id from where the metadata was published from should be incremented by 1 (one).
* a notification message should arrive from the Global Broker under `monitor/a/wis2/CENTRE_ID_global-discovery-catalogue/centre-id`)

===== Metadata ingest centre-id mismatch

====== Purpose

A Global Discovery Catalogue should detect a mismatch between an incoming message topic's centre-id and the centre-id as part of a WCMP2 record identifier.

====== Steps

. Initialize the MQTT client with the necessary parameters such as the MQTT protocol version 5, TLS security, and username/password for authentication
. Connect the MQTT client to the Global Broker
. Once the connection is successful, attempt to subscribe to the following topics:
   - ``++cache/a/wis2/+/metadata/#++``
. Check if the subscription is successful. If the subscription is successful, proceed. If the subscription is not successful, the test fails
. On an incoming message:
.. capture the centre-id from the topic (4th token split on `/`)
.. find the canonical link object in the `links` array
.. from the matching link, issue a HTTP GET request against the matching `href` value
.. parse the HTTP response:
.. extract the centre-id from WCMP2 record identifier (`id` property, 3rd token split on `:`)
.. in the WCMP2 record, if a MQTT link exists (`rel=items`, `channel` starts with `origin/a/wis2`), capture the centre-id from the topic (4th token split on `/`)
. compare the following values to verify that they are identical:
.. centre-id extracted from topic
.. centre-id extracted from WCMP2 identifier
.. centre-id extracted from MQTT link in WCMP2 record
. publish an ETS error report as a notification message to the GDC MQTT broker

On successful completion, the following metrics should be modified:

* `wmo_wis2_gdc_failed_total` for the centre-id from where the metadata was published from should be incremented by 1 (one)
* a notification message should arrive from the Global Broker under `monitor/a/wis2/CENTRE_ID_global-discovery-catalogue/centre-id`)

===== Notification and metadata processing (record deletion)

====== Purpose

The Global Discovery Catalogue should be able to process valid WCMP2 metadata record deletion of core data published by a WIS2 Node.

====== Steps

. Initialize the MQTT client with the necessary parameters such as the MQTT protocol version 5, TLS security, and username/password for authentication
. Connect the MQTT client to the Global Broker
. Once the connection is successful, attempt to subscribe to the following topics:
   - ``++cache/a/wis2/+/metadata/#++``
. Check if the subscription is successful. If the subscription is successful, proceed. If the subscription is not successful, the test fails
. On an incoming message:
.. find the link object in the `links` array where `rel=deletion`.
.. capture the `properties.metadata_id` value
.. from the matching link, issue a HTTP GET request against the matching `href` value.
.. parse the HTTP response:
... validate against the WCMP2 Executable Test Suite (ETS)
... delete the WCMP2 record from the catalogue using the value from `properties.metadata_id` captured earlier in the test
... publish a notification message to the GDC MQTT broker
.. using the WCMP2 identifier (i.e. `$WCMP2_ID`), construct a path to the record on the GDC (`\https://HOST/collections/wis2-discovery-metadata/$WCMP2_ID`)

On successful completion:

* the WCMP2 record should be removed from the GDC API
* the following metrics should be modified:
** `wmo_wis2_gdc_passed_total` for the centre-id from where the metadata was published from should be decremented by 1 (one)
** `wmo_wis2_gdc_core_total` for the centre-id from where the metadata (core data policy) was published from should be decremented by 1 (one)
* a notification message should arrive from the Global Broker under `monitor/a/wis2/CENTRE_ID_global-discovery-catalogue/centre-id`)

===== Notification and metadata processing (failure; record deletion message does not contain `properties.metadata_id`)

====== Purpose

The Global Discovery Catalogue should be able to detect a WNM error when `properties.metadata_id` is missing from a WCMP2 deletion request.

====== Steps

. Initialize the MQTT client with the necessary parameters such as the MQTT protocol version 5, TLS security, and username/password for authentication.
. Connect the MQTT client to the Global Broker
. Once the connection is successful, attempt to subscribe to the following topics:
   - ``++cache/a/wis2/+/metadata/#++``
. Check if the subscription is successful. If the subscription is successful, proceed. If the subscription is not successful, the test fails
. On an incoming message:
.. find the link object in the `links` array where `rel=deletion`
.. capture the missing `properties.metadata_id` value
.. publish a notification message of the error to the GDC MQTT broker

On successful completion:

* a notification message should arrive from the Global Broker under `monitor/a/wis2/CENTRE_ID_global-discovery-catalogue/centre-id`)

===== WCMP2 metadata archive zipfile publication

====== Purpose

Validate that a GDC API publishes a metadata archive zipfile.

====== Steps

. Construct a path to the GDC endpoint (`\https://HOST/collections/wis2-discovery-metadata`).
. Issue a HTTP GET request on the path
. Parse the HTTP response
. Check that the record includes a `links` array
. In the `links` array, check that a metadata archive zipfile link is available (where a link object's `rel=archives` and `type=application/zip`)
. In the matching link, issue a HTTP GET request on the associated `href` value
. Unzip the content of the HTTP response

On successful completion:

* the resulting HTTP response should be zip encoded data, which, when unzipped, contains a directory of JSON files of WCMP2 metadata

===== WCMP2 cold start initialization from metadata archive zipfile

====== Purpose

Validate that a GDC initializes from a metadata archive zipfile.

====== Steps

. Construct a path to an existing, functional GDC endpoint (`\https://HOST/collections/wis2-discovery-metadata`)
. Issue a HTTP GET request on the path
. Parse the HTTP response
. Check that the record includes a `links` array
. In the `links` array, check that a metadata archive zipfile link is available (where a link object's `rel=archives` and `type=application/zip`)
. In the matching link, issue a HTTP GET request on the associated `href` value
. Unzip the content of the HTTP response
. Foreach WCMP2 (JSON) record in the zipfile, validate and ingest into the new GDC
. Construct a path to the GDC endpoint (`\https://HOST/collections/wis2-discovery-metadata/items`)
. Issue a HTTP GET request on the path
. Parse the HTTP response
. Count the number of items in the `numberMatched` property

On successful completion:

* the number of the features in the GDC should match the number of records in the metadata archive zipfile.

===== API functionality

====== Purpose

Validate that a GDC API performs as expected based on the OGC API - Records standard.

====== Steps

. Construct a path to the GDC endpoint (`\https://HOST/collections/wis2-discovery-metadata`).
. Issue a HTTP GET request on the path
. Parse the HTTP response
. Check that the record includes a `links` array
. In the `links` array, check that an items link is available (where a link object's `rel=items` and `type=application/geo+json`)
. In the matching link, issue a HTTP GET request on the associated `href` value
. Parse the HTTP response
. Ensure that a `numberMatched` property exists with an integer value of 6
. Ensure that a `numberReturned` property exists with an integer value of 6
. Construct a path to the GDC endpoint with a bounding box query parameter (`\https://HOST/collections/wis2-discovery-metadata/items?bbox=-142,42,-53,84`)
. Issue a HTTP GET request on the path
. Parse the HTTP response
. Ensure that a `numberMatched` property exists with an integer value of 2
. Ensure that a `numberReturned` property exists with an integer value of 2
. Ensure that a `features` array exists
. Construct a path to the GDC endpoint with a temporal query parameter (`\https://HOST/collections/wis2-discovery-metadata/items?datetime=2000-11-11T12:42:23Z/..`)
. Issue a HTTP GET request on the path
. Parse the HTTP response
. Ensure that a `numberMatched` property exists with an integer value of 6
. Ensure that a `numberReturned` property exists with an integer value of 6
. Ensure that a `features` array exists
. Construct a path to the GDC endpoint with a full text query parameter (`\https://HOST/collections/wis2-discovery-metadata/items?q=observations`)
. Issue a HTTP GET request on the path
. Parse the HTTP response
. Ensure that a `numberMatched` property exists with an integer value of 4
. Ensure that a `numberReturned` property exists with an integer value of 4
. Ensure that a `features` array exists

==== Performance tests

===== Processing timeliness

====== Purpose

Validate that a GDC is able to process WCMP2 metadata in a timely manner.

====== Steps

. Initialize the MQTT client with the necessary parameters such as the MQTT protocol version 5, TLS security, and username/password for authentication
. Connect the MQTT client to the Global Broker
. Once the connection is successful, attempt to subscribe to the following topics:
   - ``++cache/a/wis2/+/metadata/#++``
. Check if the subscription is successful. If the subscription is successful, proceed. If the subscription is not successful, the test fails
. On all incoming messages:
.. find the canonical link object in the `links` array
.. from the matching link, issue a HTTP GET request against the matching `href` value
.. parse the HTTP response:
... validate against the WCMP2 Executable Test Suite (ETS)
... publish the WCMP2 record to the catalogue
... publish an ETS validation report as a notification message to the GDC MQTT broker.
.. using the WCMP2 identifier (i.e. `$WCMP2_ID`), construct a path to the record on the GDC (`\https://HOST/collections/wis2-discovery-metadata/$WCMP2_ID`)

On successful completion:

* all WCMP2 records should be processed and published in 5 minutes or less


==== Executing the test environment

To execute GDC tests:

[source,bash]
----
# ensure that the Python virtual environment is activated
cd tests
pytest -s global_discovery_catalogue/test_gdc_functional.py  
----


==== Exiting the test environment

The GDC implementation under test (IUT) exits the test environment with the following state:

- restoration of resources at state prior to entry:
  - metadata repository
  - metrics endpoint
  - metadata archive zipfile (create new archive file or restore from backed up file)
