[[global-discovery-catalogue-testing]]

=== Global Discovery Catalogue Service testing

==== Test setup

The GDC test setup consists of the following:

* A test data bundle to consist of:
** 100 valid WCMP2 records
** 1 broken JSON WCMP2 record
** 1 invalid WCMP2 record
** 102 WNM documents, each of which pointing to the related WCMP2 records
** 1 WNM document specifying a WCMP2 record deletion
* all WCMP2 records stored on an HTTP server
* all WNM documents updated to point to the correct HTTP server for proper HTTP dereferencing

==== Functional tests

===== Global Broker connection and subscription

====== Purpose

A Global Discovery Catalogue must connect to a Global Broker using the MQTT protocol with TLS and username/password authentication (everyone/everyone) and subscribe to the following topic:

* ``++origin/a/wis2/+/metadata/#++``

====== Steps

. Initialize the MQTT client with the necessary parameters such as the MQTT protocol version 5, TLS security, and username/password for authentication.
. Connect the MQTT client to the Global Broker.
. Once the connection is successful, attempt to subscribe to the following topics:
   - ``++origin/a/wis2/+/metadata/#++``
. Check if the subscription is successful. If the subscription is successful, proceed. If the subscription is not successful, the test fails.
. Close the connections to the broker after the test.

On successful completion, the following metrics should be modified:

* `wmo_wis2_gdc_connected_flag` for the centre-id from which the Global Discovery Catalogue connected to should be set to 1 (one).

===== Notification and metadata processing (success)

====== Purpose

The Global Discovery Catalogue should be able to process valid WCMP2 metadata record of core data published by a WIS2 Node.

====== Steps

. Initialize the MQTT client with the necessary parameters such as the MQTT protocol version 5, TLS security, and username/password for authentication.
. Connect the MQTT client to the Global Broker.
. Once the connection is successful, attempt to subscribe to the following topics:
   - ``++origin/a/wis2/+/metadata/#++``
. Check if the subscription is successful. If the subscription is successful, proceed. If the subscription is not successful, the test fails.
. On an incoming message:
.. find the canonical link object in the `links` array.
.. from the matching link, issue a HTTP GET request against the matching `href` value.
.. parse the HTTP response:
... validate against the WCMP2 Executable Test Suite (ETS)
... publish the WCMP2 record to the catalogue
... publish an ETS validation report as a notification message to the GDC MQTT broker.
.. using the WCMP2 identifier (i.e. `$WCMP2_ID`), construct a path to the record on the GDC (`\https://HOST/collections/wis2-discovery-metadata/$WCMP2_ID`).

On successful completion:

* the resulting WCMP2 record should be available on the GDC API and contain an MQTT link / channel (using `cache/a/wis2`) foreach Global Broker
* the following metrics should be modified:
** `wmo_wis2_gdc_passed_total` for the centre-id from where the metadata was published from should be incremented by 1 (one).
** `wmo_wis2_gdc_core_total` for the centre-id from where the metadata (core data policy) was published from should be incremented by 1 (one).
* a notification message should arrive from the Global Broker under `monitor/a/wis2/CENTRE_ID_global-discovery-catalogue/centre-id`)

===== Notification and metadata processing (failure; record not found)

====== Purpose

The Global Discovery Catalogue should be able to process failing (record not found) WCMP2 metadata published by a WIS2 Node.

====== Steps

. Initialize the MQTT client with the necessary parameters such as the MQTT protocol version 5, TLS security, and username/password for authentication.
. Connect the MQTT client to the Global Broker.
. Once the connection is successful, attempt to subscribe to the following topics:
   - ``++origin/a/wis2/+/metadata/#++``
. Check if the subscription is successful. If the subscription is successful, proceed. If the subscription is not successful, the test fails.
. On an incoming message:
.. find the canonical link object in the `links` array.
.. from the matching link, issue a HTTP GET request against the matching `href` value.
.. if the response is an HTTP status code of 404:
... publish an ETS error report as a notification message to the GDC MQTT broker.

On successful completion:

* the following metrics should be modified:
** `wmo_wis2_gdc_failed_total` for the centre-id from where the metadata was published from should be incremented by 1 (one).
* a notification message should arrive from the Global Broker under `monitor/a/wis2/CENTRE_ID_global-discovery-catalogue/centre-id`)

===== Notification and metadata processing (failure; malformed JSON)

====== Purpose

The Global Discovery Catalogue should be able to process failing (malformed JSON) WCMP2 metadata published by a WIS2 Node.

====== Steps

. Initialize the MQTT client with the necessary parameters such as the MQTT protocol version 5, TLS security, and username/password for authentication.
. Connect the MQTT client to the Global Broker.
. Once the connection is successful, attempt to subscribe to the following topics:
   - ``++origin/a/wis2/+/metadata/#++``
. Check if the subscription is successful. If the subscription is successful, proceed. If the subscription is not successful, the test fails.
. On an incoming message:
.. find the canonical link object in the `links` array.
.. from the matching link, issue a HTTP GET request against the matching `href` value.
.. parse the HTTP response:
.. if the JSON is malformed:
... publish an ETS error report as a notification message to the GDC MQTT broker.

On successful completion:

* the following metrics should be modified:
** `wmo_wis2_gdc_failed_total` for the centre-id from where the metadata was published from should be incremented by 1 (one).
* a notification message should arrive from the Global Broker under `monitor/a/wis2/CENTRE_ID_global-discovery-catalogue/centre-id`)

===== Notification and metadata processing (failure; invalid WCMP2 record)

TODO: we need more examples of invalid WCMP2



====== Purpose

The Global Discovery Catalogue should be able to process failing WCMP2 metadata published by a WIS2 Node.

====== Steps

. Initialize the MQTT client with the necessary parameters such as the MQTT protocol version 5, TLS security, and username/password for authentication.
. Connect the MQTT client to the Global Broker.
. Once the connection is successful, attempt to subscribe to the following topics:
   - ``++origin/a/wis2/+/metadata/#++``
. Check if the subscription is successful. If the subscription is successful, proceed. If the subscription is not successful, the test fails.
. On an incoming message:
.. find the canonical link object in the `links` array.
.. from the matching link, issue a HTTP GET request against the matching `href` value.
.. parse the HTTP response:
... validate against the WCMP2 Executable Test Suite (ETS)
... publish an ETS error report as a notification message to the GDC MQTT broker.

On successful completion:

* the following metrics should be modified:
** `wmo_wis2_gdc_failed_total` for the centre-id from where the metadata was published from should be incremented by 1 (one).
* a notification message should arrive from the Global Broker under `monitor/a/wis2/CENTRE_ID_global-discovery-catalogue/centre-id`)

===== Metadata ingest centre-id mismatch


TODO: validate workflow for regional distribution of partner metadata



====== Purpose

A Global Discovery Catalogue should detect a mismatch between an incoming message topic's centre-id and the centre-id as part of a WCMP2 record identifier.

====== Steps

. Initialize the MQTT client with the necessary parameters such as the MQTT protocol version 5, TLS security, and username/password for authentication.
. Connect the MQTT client to the Global Broker.
. Once the connection is successful, attempt to subscribe to the following topics:
   - ``++origin/a/wis2/+/metadata/#++``
. Check if the subscription is successful. If the subscription is successful, proceed. If the subscription is not successful, the test fails.
. On an incoming message:
.. capture the centre-id from the topic (4th token split on `/`).
.. find the canonical link object in the `links` array.
.. from the matching link, issue a HTTP GET request against the matching `href` value.
.. parse the HTTP response:
.. extract the centre-id from WCMP2 record identifier (3rd token split on `:`).
. compare the centre-id from the topic and the centre-id of the WCMP2 record identifier.
. publish an ETS error report as a notification message to the GDC MQTT broker.

On successful completion, the following metrics should be modified:

* `wmo_wis2_gdc_failed_total` for the centre-id from where the metadata was published from should be incremented by 1 (one).
* a notification message should arrive from the Global Broker under `monitor/a/wis2/CENTRE_ID_global-discovery-catalogue/centre-id`)

===== Notification and metadata processing (record deletion)

====== Purpose

The Global Discovery Catalogue should be able to process valid WCMP2 metadata record deletion of core data published by a WIS2 Node.

====== Steps

. Initialize the MQTT client with the necessary parameters such as the MQTT protocol version 5, TLS security, and username/password for authentication.
. Connect the MQTT client to the Global Broker.
. Once the connection is successful, attempt to subscribe to the following topics:
   - ``++origin/a/wis2/+/metadata/#++``
. Check if the subscription is successful. If the subscription is successful, proceed. If the subscription is not successful, the test fails.
. On an incoming message:
.. find the deletion link object in the `links` array.
.. from the matching link, issue a HTTP GET request against the matching `href` value.
.. parse the HTTP response:
... validate against the WCMP2 Executable Test Suite (ETS)
... delete the WCMP2 record from the catalogue
... publish a notification message to the GDC MQTT broker.
.. using the WCMP2 identifier (i.e. `$WCMP2_ID`), construct a path to the record on the GDC (`\https://HOST/collections/wis2-discovery-metadata/$WCMP2_ID`).

On successful completion:

* the WCMP2 record should be removed from the GDC API
* the following metrics should be modified:
** `wmo_wis2_gdc_passed_total` for the centre-id from where the metadata was published from should be decremented by 1 (one).
** `wmo_wis2_gdc_core_total` for the centre-id from where the metadata (core data policy) was published from should be decremented by 1 (one).
* a notification message should arrive from the Global Broker under `monitor/a/wis2/CENTRE_ID_global-discovery-catalogue/centre-id`)

BEGIN
TODO test deletion WITHOUT metadata_id
END

BEGIN
TODO add test case for metadata zipfile usage on cold start
END


===== WCMP2 metadata archive zipfile publication

====== Purpose

Validate that a GDC API publishes a metadata archive zipfile.

====== Steps

. Construct a path to the GDC endpoint (`\https://HOST/collections/wis2-discovery-metadata`).
. Issue a HTTP GET request on the path.
. Parse the HTTP response.
. Check that the record includes a `links` array.
. In the `links` array, check that a metadata archive zipfile link is available (where a link object's `rel=archives` and `type=application/zip`).
. In the matching link, issue a HTTP GET request on the associated `href` value.
. Unzip the content of the HTTP response.
. Initialize the MQTT client with the necessary parameters such as the MQTT protocol version 5, TLS security, and username/password for authentication.
. Connect the MQTT client to the Global Discovery Catalogue.
. Once the connection is successful, attempt to subscribe to the following topics:
   - ``++origin/a/wis2/centre-id/metadata/#++`` (where `centre-id` is the centre identifier of the Global Discovery Catalogue).
. Check if the subscription is successful. If the subscription is successful, proceed. If the subscription is not successful, the test fails.
. If the MQTT client is able to successfully subscribe to the topic on the Global Discovery Catalogue, the test passes. If not, the test fails.
. On receipt of a notification message, issue a HTTP GET requerst on the canonical link (a link object's `href` property where `rel=canonical`)
. Unzip the content of the HTTP response.

On successful completion:

* the resulting HTTP response should be a zip encoded data, which, when unzipped, contains a directory of JSON files of WCMP2 metadata.

===== OpenMetrics publication

====== Purpose

Validate that a GDC API publishes an OpenMetrics endpoint.

====== Steps

. Construct a path to the GDC endpoint (`\https://HOST/collections/wis2-discovery-metadata`).
. Issue a HTTP GET request on the path.
. Parse the HTTP response.
. Check that the record includes a `links` array.
. In the `links` array, check that a metadata archive zipfile link is available (where a link object's `rel=related`, `type=text/plain` and `title=OpenMetrics`.
. In the matching link, issue a HTTP GET request on the associated `href` value.
. Parse the HTTP response.

On successful completion:

* the resulting HTTP response should be a text file in OpenMetrics format.

===== API functionality

====== Purpose

Validate that a GDC API performs as expected based on the OGC API - Records standard.

====== Steps

. Construct a path to the GDC endpoint (`\https://HOST/collections/wis2-discovery-metadata`).
. Issue a HTTP GET request on the path.
. Parse the HTTP response.
. Check that the record includes a `links` array.
. In the `links` array, check that an items link is available (where a link object's `rel=items` and `type=application/geo+json`).
. In the matching link, issue a HTTP GET request on the associated `href` value.
. Parse the HTTP response.
. Ensure that a `numberMatched` property exists with an integer value greater than 0.
. Ensure that a `numberReturned` property exists with an integer value greater than 0.
. Construct a path to the GDC endpoint with a bounding box query parameter (`\https://HOST/collections/wis2-discovery-metadata?bbox=-142,42,-53,84`).
. Issue a HTTP GET request on the path.
. Parse the HTTP response.
. Ensure that a `numberMatched` property exists with an integer value greater than 0.
. Ensure that a `numberReturned` property exists with an integer value greater than 0.
. Ensure that a `features` array exists.
. Construct a path to the GDC endpoint with a temporal query parameter (`\https://HOST/collections/wis2-discovery-metadata?datetime=2000-11-11T12:42:23Z/..`).
. Issue a HTTP GET request on the path.
. Parse the HTTP response.
. Ensure that a `numberMatched` property exists with an integer value greater than 0.
. Ensure that a `numberReturned` property exists with an integer value greater than 0.
. Ensure that a `features` array exists.
. Construct a path to the GDC endpoint with a full text query parameter (`\https://HOST/collections/wis2-discovery-metadata?q=observations`).
. Issue a HTTP GET request on the path.
. Parse the HTTP response.
. Ensure that a `numberMatched` property exists with an integer value greater than 0.
. Ensure that a `numberReturned` property exists with an integer value greater than 0.
. Ensure that a `features` array exists.

TODO: measure accuracy

==== Performance tests

===== Processing timeliness

====== Purpose

Validate that a GDC is able to process WCMP2 metadata in a timely manner.

====== Steps

. Initialize the MQTT client with the necessary parameters such as the MQTT protocol version 5, TLS security, and username/password for authentication.
. Connect the MQTT client to the Global Broker.
. Once the connection is successful, attempt to subscribe to the following topics:
   - ``++origin/a/wis2/+/metadata/#++``
. Check if the subscription is successful. If the subscription is successful, proceed. If the subscription is not successful, the test fails.
. On all incoming messages:
.. find the canonical link object in the `links` array.
.. from the matching link, issue a HTTP GET request against the matching `href` value.
.. parse the HTTP response:
... validate against the WCMP2 Executable Test Suite (ETS)
... publish the WCMP2 record to the catalogue
... publish an ETS validation report as a notification message to the GDC MQTT broker.
.. using the WCMP2 identifier (i.e. `$WCMP2_ID`), construct a path to the record on the GDC (`\https://HOST/collections/wis2-discovery-metadata/$WCMP2_ID`).

On successful completion:

* all WCMP2 records should be processed and published in 5 minutes
