[[global-discovery-catalogue-testing]]

=== Global Discovery Catalogue Service testing

==== Functional tests

===== MQTT Connectivity

====== Purpose

An MQTT client must be able to connect to the local broker of the Global Discovery Catalogue on port 8883 using the MQTT protocol version 5 with TLS (i.e., mqtts protocol) and username/password authentication.

====== Steps

. Initialize the MQTT client with the necessary parameters such as the MQTT protocol version 5, TLS security, and username/password for authentication.
. Attempt to connect the MQTT client to the local broker of the Global Discovery Catalogue on port 8883.
. Check if the connection is successful. If the connection is successful, the test passes. If the connection is not successful, the test fails.
. Close the connection to the broker after the test.

===== Client subscription

====== Purpose

A Global Discovery Catalogue must allow connected MQTT clients to subscribe to the `monitor/a/wis2/#` topic.

====== Steps

. Initialize the MQTT client with the necessary parameters such as the MQTT protocol version 5, TLS security, and username/password for authentication.
. Connect the MQTT client to the local broker of the Global Discovery Catalogue.
. Once the connection is successful, attempt to subscribe to the `monitor/a/wis2/#` topic.
. Check if the subscription is successful. If the subscription is successful, the test passes. If the subscription is not successful, the test fails.
. Close the connection to the broker after the test.

===== Global Broker subscription

====== Purpose

A Global Discovery Catalogue must connect to a Global Broker using the MQTT protocol with TLS and username/password authentication (everyone/everyone) and subscribe to the following topic:

* ``++origin/a/wis2/+/metadata/#++``

====== Steps

. Initialize the MQTT client with the necessary parameters such as the MQTT protocol version 5, TLS security, and username/password for authentication.
. Connect the MQTT client to the Global Broker.
. Once the connection is successful, attempt to subscribe to the following topics:
   - ``++origin/a/wis2/+/metadata/#++``
. Check if the subscription is successful. If the subscription is successful, proceed. If the subscription is not successful, the test fails.
. Close the connections to the broker after the test.

On successful completion, the following metrics should be modified:

* `wmo_wis2_gdc_connected_flag` for the centre-id frmo which the Global Discovery Catalogue connected to should be set to 1 (one).

===== Notification and metadata processing (success)

====== Purpose

The Global Discovery Catalogue should be able to:

* process an incoming notification message.
* download the metadata at the canonical link.
* validate the valid metadata against the WCMP2 Executable Test Suite (ETS).
* publish an ETS validation report notification message on the proper topic using the proper message structure.
* evaluate the metadata against the WCMP2 Key Performance Indicators (KPI).
* publish a KPI evaluation report notification message on the proper topic using the proper message structure.
* update the necessary metrics.

The WCMP2 record published by the Global Discovery Catalogue should be identical to the content of the canonical link referenced from notification message received, except for the following:

* for core data, add/replace link objects on core data notifications to reference each WIS2 Global Broker using the associated cached topic.

On successful completion, the following metrics should be modified:

* `wmo_wis2_gdc_passed_total` for the centre-id from where the metadata was published from should be incremented by 1 (one).
* `wmo_wis2_gdc_core_total` for the centre-id from where the metadata (core data policy) was published from should be incremented by 1 (one).
* `wmo_wis2_gdc_recommended_total` for the centre-id from where the metadata (recommended data policy) was published from should be incremented by 1 (one).
* `wmo_wis2_gdc_kpi_percentage_total` for the centre-id from where the metadata was published from should be incremented by 1 (one).
* `wmo_wis2_gdc_kpi_percentage_average` for the centre-id from where the metadata was published from should be calculated as an average.
* `wmo_wis2_gdc_kpi_percentage_over80_total` for the centre-id from where the metadata was published from should be incremented by 1 (one).

===== Notification and metadata processing (failure)

====== Purpose

The Global Discovery Catalogue should be able to:

====== Steps

* process an incoming notification message.
* download the metadata at the canonical link.
* validate the invalid failing metadata against the WCMP2 Executable Test Suite (ETS).
* publish an ETS validation report notification message on the proper topic using the proper message structure.
* update the necessary metrics.

On successful completion, the following metrics should be modified:

* `wmo_wis2_gdc_failed_total` for the centre-id from where the metadata was published from should be incremented by 1 (one).

===== Metadata ingest topic mismatch

====== Purpose

A Global Discovery Catalogue should detect a mismatch between an incoming message topic's centre-id and the centre-id as part of a WCMP2 record identifier.

====== Steps

* process an incoming notification message.
* extract the centre-id from the topic (4th token split on `/`).
* download the metadata at the canonical link.
* extract the centre-id from WCMP2 record identifier (3rd token split on `:`).
* compare the centre-id from the topic and the centre-id of the WCMP2 record identifier.
* publish an error report to `monitor/a/wis2/`

On successful completion, the following metrics should be modified:

* `wmo_wis2_gdc_failed_total` for the centre-id from where the metadata was published from should be incremented by 1 (one).

===== WCMP2 metadata archive zipfile publication

====== Purpose

Validate that a GDC API publishes a metadata archive zipfile.

====== Steps

. Construct a path to the GDC endpoint (`\https://HOST/collections/wis2-discovery-metadata`).
. Issue a HTTP GET request on the path.
. Parse the HTTP response.
. Check that the record includes a `links` array.
. In the `links` array, check that a metadata archive zipfile link is available (where a link object's `rel=enclosure` and `type=application/zip`).
. In the matching link, issue a HTTP GET request on the associated `href` value.
. Unzip the content of the HTTP response.
. Initialize the MQTT client with the necessary parameters such as the MQTT protocol version 5, TLS security, and username/password for authentication.
. Connect the MQTT client to the Global Discovery Catalogue.
. Once the connection is successful, attempt to subscribe to the following topics:
   - ``++origin/a/wis2/centre-id/metadata/#++`` (where `centre-id` is the centre identifier of the Global Discovery Catalogue).
. Check if the subscription is successful. If the subscription is successful, proceed. If the subscription is not successful, the test fails.
. If the MQTT client is able to successfully subscribe to the topic on the Global Discovery Catalogue, the test passes. If not, the test fails.
. On receipt of a notification message, issue a HTTP GET requerst on the canonical link (a link object's `href` property where `rel=canonical`)
. Unzip the content of the HTTP response.
. Close the connection to the broker after the test.

===== OpenMetrics publication

====== Purpose

Validate that a GDC API publishes an OpenMetrics endpoint.

====== Steps

. Construct a path to the GDC endpoint (`\https://HOST/collections/wis2-discovery-metadata`).
. Issue a HTTP GET request on the path.
. Parse the HTTP response.
. Check that the record includes a `links` array.
. In the `links` array, check that a metadata archive zipfile link is available (where a link object's `rel=related`, `type=text/plain` and `title=OpenMetrics`.
. In the matching link, issue a HTTP GET request on the associated `href` value.
. Unzip the content of the HTTP response.


===== API functionality

====== Purpose

Validate that a GDC API performs as expected based on the OGC API - Records standard.

====== Steps

. Construct a path to the GDC endpoint (`\https://HOST/collections/wis2-discovery-metadata`).
. Issue a HTTP GET request on the path.
. Parse the HTTP response.
. Check that the record includes a `links` array.
. In the `links` array, check that an items link is available (where a link object's `rel=items` and `type=application/geo+json`).
. In the matching link, issue a HTTP GET request on the associated `href` value.
. Parse the HTTP response.
. Ensure that a `numberMatched` property exists with an integer value greater than 0.
. Ensure that a `numberReturned` property exists with an integer value greater than 0.
. Construct a path to the GDC endpoint with a bounding box query parameter (`\https://HOST/collections/wis2-discovery-metadata?bbox=-142,42,-53,84`).
. Issue a HTTP GET request on the path.
. Parse the HTTP response.
. Ensure that a `numberMatched` property exists with an integer value greater than 0.
. Ensure that a `numberReturned` property exists with an integer value greater than 0.
. Ensure that a `features` array exists.
. Construct a path to the GDC endpoint with a temporal query parameter (`\https://HOST/collections/wis2-discovery-metadata?datetime=2000-11-11T12:42:23Z/..`).
. Issue a HTTP GET request on the path.
. Parse the HTTP response.
. Ensure that a `numberMatched` property exists with an integer value greater than 0.
. Ensure that a `numberReturned` property exists with an integer value greater than 0.
. Ensure that a `features` array exists.
. Construct a path to the GDC endpoint with a full text query parameter (`\https://HOST/collections/wis2-discovery-metadata?q=observations`).
. Issue a HTTP GET request on the path.
. Parse the HTTP response.
. Ensure that a `numberMatched` property exists with an integer value greater than 0.
. Ensure that a `numberReturned` property exists with an integer value greater than 0.
. Ensure that a `features` array exists.

==== Performance tests

===== API performance

====== Purpose

Validate that a GDC API peforms

====== Steps

. step 1
. step 2
