[[global-monitor-testing]]

=== Global Monitor Service testing

==== Functional tests

===== Connectivity

====== Purpose
A Global Monitor must connect to the endpoints provided by the other Global Services, and if any of the endpoints is unavailable, the error should be reported and the alert notification messages should arrive.

TODO

====== Steps

. Initialize the MQTT client with the necessary parameters such as the MQTT protocol version 5, TLS security, and username/password for authentication.
. Connect the MQTT client to the broker of GM.
. Once the connection is successful, attempt to subscribe to the following topics:
- ``++monitor/a/wis2/#++``
. Initialize the GM with test endpoint with simulated metrics.
. Check if the endpoint is available, if it is, it shows ‘UP’ on the webpage. 
. If the endpoint is unavailable, it shows error just like '404' on the webpage, and a notification message should arrive from the broker of GM under

 - ``++monitor/a/wis2/CENTRE_ID-global-monitor/centre-id++``

* e.g. monitor/a/wis2/cn-cma-global-monitor/us-noaa-nws-global-broker

===== Metrics validation （failure; invalid）

====== Purpose
The Global Monitor should be able to recognize the invalid metrics, give prompt and alert.

TODO

====== Steps

. Initialize the MQTT client with the necessary parameters such as the MQTT protocol version 5, TLS security, and username/password for authentication.
. Connect the MQTT client to the broker of GM.
. Once the connection is successful, attempt to subscribe to the following topics:
 - ``++monitor/a/wis2/#++``
. Initialize the GM with test endpoint with invalid metrics.
. GM gives the error prompt on the webpage, and a notification message should arrive from the broker of GM under

 - ``++monitor/a/wis2/CENTRE_ID-global-monitor/centre-id++``

* e.g. monitor/a/wis2/ma-marocmeteo-global-monitor/us-noaa-nws-global-broker

===== Display the metrics on the dashboard

====== Purpose
The metrics that scraped from the Global Services could be displayed on the dashboard appropriately.

TODO

====== Steps

. Initialize the GM with the endpoints with valid metrics.
. Open the corresponding dashboard, if the dashboard could display the metrics in an appropriate way, it is successful. 

===== Raising alert 1

====== Purpose
The Global Monitor could raise the alert according to the metrics and the alerting rules.

TODO

====== Steps

. Simulate the metrics, and set wmo_wis2_gb_connected_flag{centre_id="int-ecmwf"} = 0 reported by 3 Global Brokers.
. Publish the metrics once per minute.
. Configure gb.yml
|===
alert: disconnectedwis2nodemultiplegb

expr: count by (centre_id) ( wmo_wis2_gb_connected_flag == 0 ) > 1

for: 2m

labels:

severity: error

annotations:

summary: Disconnected WIS2 Node from multiple Global Brokers
|===
. Wait for 2 minutes, and watch the webpage, if the alert is raised on the webpage, it is successful, otherwise, it is unsuccessful.
. Initialize the MQTT client with the necessary parameters such as the MQTT protocol version 5, TLS security, and username/password for authentication.
. Connect the MQTT client to the broker of GM.
. Once the connection is successful, attempt to subscribe to the following topics:
 - ``++monitor/a/wis2/#++``
. An alert notification message should arrive from the broker of GM under
 - ``++monitor/a/wis2/CENTRE_ID-global-monitor/int-ecmwf``

===== Raising alert 2

====== Purpose
The Global Monitor could raise the alert according to the metrics and the alerting rules.

TODO

====== Steps

. Simulate the metrics, and set wmo_wis2_gc_downloaded_total = 0 reported by cn-cma-global-cache.
. Publish the metrics once per minute.
. Configure the gc.yml
|===
No data is received by Global Cache over the two minutes

     - alert: No_data

       expr: sum by (report_by) (delta(wmo_wis2_gc_downloaded_total[2m])) == 0

        for: 2m

        labels:

          severity: critical

        annotations:

          summary: The Global cache is not receiving any data since two minutes
|===
. Wait for 2 minutes, and watch the webpage, if the alert is raised on the webpage, it is successful, otherwise, it is unsuccessful.
. Initialize the MQTT client with the necessary parameters such as the MQTT protocol version 5, TLS security, and username/password for authentication.
. Connect the MQTT client to the broker of GM.
. Once the connection is successful, attempt to subscribe to the following topics:
 - ``++monitor/a/wis2/#++``
. An alert notification message should arrive from the broker of GM under
 - ``++monitor/a/wis2/CENTRE_ID_global-monitor/cn-cma-global-cache++``

==== Performance tests

===== multiple providers

====== Purpose
A Global Monitor should support a minimum of 50 metrics providers.

TODO

====== Steps

. Set up the configuration with 50 simulated endpoints.
. If all the endpoints shows 'UP' on the webpage, the test passes.
. Open the dashboard and check if it matches the metrics, if it is, the test passes.

===== simultaneous access

====== Purpose
A Global Monitor should support 200 simultaneous access to the dashboard

TODO

====== Steps

. Open Jmeter and configure the Test Plan: 
- GM address, username and password
- threads(=200)
- Ramp-up Time and Loop Count(=30s)
- Add listener
- Run the test
. When the test finishe­s, look at the results in the liste­ners. Look at things like response­ time, throughput, and error rate. 
