[[global-monitor-testing]]

=== Global Monitor Service testing

==== Functional tests

===== Connectivity

====== Purpose
A Global Monitor must connect to the endpoints provided by the other Global Services, and if any of the endpoints is unavailable, the error should be reported and the alert notification messages should arrive.

TODO

====== Steps

. Initialize the MQTT client with the necessary parameters such as the MQTT protocol version 5, TLS security, and username/password for authentication.
. Connect the MQTT client to the broker of GM.
. Once the connection is successful, attempt to subscribe to the following topics:
  ``++monitor/a/wis2/#++``
. Initialize the GM with test endpoint with simulated metrics.
. Check if the endpoint is available, if it is, it shows ‘UP’ on the webpage. 
. If the endpoint is unavailable, it shows error just like '404' on the webpage, and a notification message should arrive from the broker of GM under

  ``++monitor/a/wis2/CENTRE_ID_global-monitor/centre-id++``

* e.g. monitor/a/wis2/cn-cma-global-monitor/us-noaa-nws-globalbroker

===== Metrics validation （failure; invalid）

====== Purpose
The Global Monitor should be able to recognize the invalid metrics, give prompt and alert.

TODO

====== Steps

. Initialize the MQTT client with the necessary parameters such as the MQTT protocol version 5, TLS security, and username/password for authentication.
. Connect the MQTT client to the broker of GM.
. Once the connection is successful, attempt to subscribe to the following topics:
  ``++monitor/a/wis2/#++``
. Initialize the GM with test endpoint with invalid metrics.
. GM gives the error prompt on the webpage, and a notification message should arrive from the broker of GM under

  ``++monitor/a/wis2/CENTRE_ID_global-monitor/centre-id++``

* e.g. monitor/a/wis2/cn-cma_global-monitor/us-noaa-nws-globalbroker









==== Performance tests

===== Test name

====== Purpose

TODO

====== Steps

. step 1
. step 2
