[[global-broker-testing]]

=== Global Broker Service testing

All Global Services, and in particular Global Brokers and Global Caches, are collectively responsible in making the WIS a reliable and efficient mean to exchange
data required for the operations of all WIS Centres. The agreed architecture provides a redundant solution where the failure of one component will not impact the overall level of service of WIS.  Each Global Service should aim at achieving at least 99.5% availability of the service they propose. This is not a contractual target. It should be considered by the entity providing the Global Service as a guideline when designing and operating the Global Service.

A Global Broker:

- should support a minimum of *200* WIS2 Nodes or Global Services
- should support a minimum of *1000* subscribers.
- should support processing of a minimum of *10000* messages per second

==== Setup and tear down Global Brokers for the tests

It has been decided to rely on _-test_ systems to emulate WIS2 Nodes. 
Two kinds of test WIS2 Nodes have been prepared.

- 10 WIS2 Nodes for functional tests
- 200 WIS2 Nodes for performance tests

===== For the functional tests
Ten WIS2 Nodes are deployed on AWS;
The DNS names of the WIS2 nodes will be:

- test-node-1.wis2dev.io

- test-node-2.wis2dev.io

...

- test-node-10.wis2dev.io

The _centre_id_ for these WIS2 Nodes will be *io-wis2dev-11-test* (on test-node-1 host) to *io-wis2dev-20-test* (on test-node-10 host).

They will be used during the functional tests of the Global Broker.

===== For the performance tests

Two hundred WIS2 Nodes, only for WIS2 Notification Messages, will be deployed on 5 of the same VMs. On each VM, the equivalent of 40 WIS2 Nodes will be deployed. They will share the same MQTT Broker, however the _centre_id_ and the subscription topic will be different for each WIS2 Node.

The DNS name of the VM will be:

- test-node-1.wis2dev.io (for centre_id from 100 to 139)

- test-node-2.wis2dev.io (for centre_id from 140 to 179)

...

- test-node-5.wis2dev.io (for centre_id from 260 to 299)

===== MQTT Configuration 

The MQTT broker(s) will be reachable using:

```
MQTT_SUB_BROKER=mqtt://test-node-1.wis2dev.io (and also -2, -3,... -10)
MQTT_SUB_USERNAME=everyone
MQTT_SUB_PASSWORD=onlyone
```

1. Default MQTT port will be used (1883)
2. The password is changed to _onlyone_. This allows to prevent the default authentication (everyone/everyone) to be usable, while keeping the authorization (typically using only the username) unchanged

===== Notification Message tests

As no metadata record will be provided, checking the existence of the metadata record by the Global Broker must be disabled.

As the topic used for the test messages will be correct, checking the validity of the Topic Hierarchy must be done.

As the Notification Messages will be syntactically correct, checking the compliance of the Notification Message with the defined schema (schemas.wmo.int) must be done.

===== centre_id and subscription

The centre_id will be of the from io-wis2dev-[number]-test with number varying from 11 to 20, and 100 to 299. 100 to 139 on test-node-1.wis2dev.io and so on.

Messages will be published on the topic `origin/a/wis2/io-wis2dev-x-test/#` (with x varying from 11 to 20 and 100 to 299).

===== Summary

Using the antiloop software used by Brazil and France, as an example, the configuration file _io-wis2dev-100-test.env_ will be : 

```
MQTT_SUB_BROKER=mqtt://test-node-1.wis2dev.io
MQTT_SUB_USERNAME=everyone
MQTT_SUB_PASSWORD=onlyone
MQTT_SUB_TOPIC=origin/a/wis2/io-wis2dev-100-test/#
CENTRE_ID=io-wis2dev-100-test
MSG_CHECK_OPTION=verify
TOPIC_CHECK_OPTION=verify
METADATA_CHECK_OPTION=no
GDC_URL=https://wis2-gdc.weather.gc.ca/collections/wis2-discovery-metadata/items?lang=en&f=json&q=
SCHEMA_URL=https://raw.githubusercontent.com/wmo-im/wis2-notification-message/main/schemas/wis2-notification-message-bundled.json
```

The configuration file _io-wis2dev-210-test.env_ will be : 

```
MQTT_SUB_BROKER=mqtt://test-node-3.wis2dev.io
MQTT_SUB_USERNAME=everyone
MQTT_SUB_PASSWORD=onlyone
MQTT_SUB_TOPIC=origin/a/wis2/io-wis2dev-210-test/#
CENTRE_ID=io-wis2dev-210-test
MSG_CHECK_OPTION=verify
TOPIC_CHECK_OPTION=verify
METADATA_CHECK_OPTION=no
GDC_URL=https://wis2-gdc.weather.gc.ca/collections/wis2-discovery-metadata/items?lang=en&f=json&q=
SCHEMA_URL=https://raw.githubusercontent.com/wmo-im/wis2-notification-message/main/schemas/wis2-notification-message-bundled.json
```
Summary of the correspondance between the MQTT endpoint address and centre_id:

- WIS2 Node 100 to 139 on test-node-1.wis2dev.io
- WIS2 Node 140 to 179 on test-node-2.wis2dev.io
- WIS2 Node 180 to 219 on test-node-3.wis2dev.io
- WIS2 Node 220 to 259 on test-node-4.wis2dev.io
- WIS2 Node 260 to 299 on test-node-5.wis2dev.io

Ahead of the testing period, each Global Broker operator is invited to prepare the configuration for the 210 (10 + 200) WIS2 Nodes.

==== Setup the Global Broker for the tests

In order to run the tests, the operators of the Global Broker will need to:

1. Remove all the subscriptions to existing and _real_ WIS2 Nodes 
2. Modify the password of the _everyone_ user on the broker of the Global Broker from *everyone* to *onlyone*
3. Delete all existing subscriptions to broker of the Global Broker (Users, other Global Brokers, Global Caches have a subscription to the broker)
4. Enable all configurations to the _test_ 210 WIS2 nodes

Depending on the Global Broker and the MQTT broker used, the method of doing the four steps above will be different and is beyond the scope of this document. 

When those steps are completed, the Global Broker will be ready to run the functional and performance tests.

==== Tear down the Global Broker to reverse WIS2 operations

After the performance tests, the operators of the Global Broker will need to:

1. Remove all the subscriptions to _-test_ WIS2 Nodes 
2. Modify the password of the _everyone_ user on the broker of the Global Broker from *onlyone* to *everyone*
3. Delete all existing subscriptions to broker of the Global Broker 
4. Enable all configurations to the _real_ WIS2 nodes

Depending on the Global Broker and the MQTT broker used, the method of doing the four steps above will be different and is beyond the scope of this document. 

When those steps are completed, the Global Broker will be back to normal operations.

==== Functional tests

===== Port

====== Purpose

An MQTT client must be able to connect to the local broker of the Global Broker on ports 8883 (MQTTS) or 443 (WSS) using the agreed protocols with Transport Layer Security (TLS) and username/password authentication. 

====== Requirements

* Global Broker MQTT details.
* MQTT Test Client

====== Steps

. Initialise the test MQTT client with the necessary parameters such as the MQTT protocol, TLS security, and username/password for authentication (connection string).
. Attempt to connect the MQTT broker of the Global Broker using the connection string.

====== Evaluate

. Check if the connection is successful.

===== Certificate

====== Purpose

The Global Broker service must use a valid certificate.  Transport Layer Security (TLS) is an encryption protocol that provides secure connections between servers and applications on the internet.

====== Requirements

* Global Broker MQTT connection string
* MQTT Test Client (If used, MQTT Explorer needs to import the Certificate Authority used by the Global Broker to check that the certificate is valid) or a browser like Firefox.

====== Steps

From the client and try to connect to a Global Broker using WSS protocol.  The Global Broker sends the MQTT client its TLS certificate.  The MQTT client then verifies that the certificate is valid and digitally signed by a trusted CA by comparing it with information it stores about trusted CAs. The signed certificate verifies the website server’s public key, which confirms that you’re communicating with the genuine server of the website you’re visiting.  The server also authenticates a key exchange, resulting in a one-time session key that is used to send encrypted and authenticated data between the clients and the server.
If a browser like Firefox is used, connect WSS endpoint (https://globalbroker.example.org/mqtt). In the address bar, a lock is displayed.

====== Evaluate

. Check if the TLS connection is successful 
. Check for certification verification.

If the connection is successful and the certificate are valid, the test passes. If the connection is not successful or the certificate is invalid, the test fails.

===== Origin and Cache Read-Access

====== Purpose

The Global Broker service must allow [.underline]#only# read access to _origin/a/wis2/#_ and _cache/a/wis2/#_ using a username and password credential of everyone/everyone 

====== Requirements

* Global Broker MQTT connection string
* MQTT Test Client

====== Steps

. From a MQTT client, set up a new connection to the Global Broker, with the following configuration settings:   
. Configure 2 subscriptions.  First, create separate subscriptions for _origin/a/wis2/#_ and _cache/a/wis2/#_ using a username and password credential for "everyone/everyone"
. Save the configuration and click connect

====== Evaluate

Check if the connection is successful, and depending on the flow of messages, messages should appear rapidly.  If messages are displayed, the test passes. If the connection is not successful, the test fails.

===== Deny write access to _origin/a/wis2/#_ and _cache/a/wis2/#_ for everyone/everyone credentials

====== Purpose

The Global Broker service must prevent write access to any topic with everyone/everyone credentials 

====== Requirements

* Global Broker MQTT connection string
* MQTT Test Client

====== Steps

. Use an MQTT client to connect to Global Broker
. Try to publish data or metadata to Global Broker

====== Evaluate

Check if the connection is successful, and the publication fails or the connection drops, the test is successful. If the connection is successful, and the publication is allowed, the test fails.

===== cluster redundancy

====== Purpose

The Global Broker service, should be using a MQTT server deployed in a cluster, then the MQTT Broker must use a redundant load balancing service so that the service in maintained in case of failure of one entity of the cluster 

====== Requirements

* Global Broker MQTT connection string
* MQTT Test Client

====== Steps

. From a MQTT client, set up a new subscription to either "origin/a/wis2/" and "cache/a/wis2/" using a username and password credential for "everyone/everyone".  
. Fail a member of the cluster and ensure that subscriptions are still being fulfilled

====== Evaluate

. Check if the subscription is successful even after the members of the cluster are failed. If the subscription continues as cluster is altered, the test passes. If the subscription is not fulfilled after cluster alternation, the test fails.

===== Discarding of duplicate messages

====== Purpose

The Global Broker service must discard all duplicated messages (identical id) received whatever the originator of the messages 

====== Requirements

* The container https://hub.docker.com/r/golfvert/fakewis2node deployed on 10 tests system (*io-wis2dev-11-test* to *io-wis2dev-20-test*)
* Global Broker MQTT connection string to 2 WIS2 Nodes (with the following centre_id: io-wis2dev-11-test and io-wis2dev-12-test)
* MQTT Test Client subscribed to *origin/a/wis2/io-wis2dev-11-test/#* and *origin/a/wis2/io-wis2dev-20-test/*

====== Steps

. WIS2Node _io-wis2dev-11-test_ publish on its local broker *ten* messages with a pre-defined id (using the UUID format) on topic *origin/a/wis2/io-wis2dev-11-test/core/data/weather/surface-based-observation/synop*
. WIS2Node _io-wis2dev-12-test_ publish *ten* message with the same id (same id as above) on topic *origin/a/io-wis2dev-12-test/core/data/weather/surface-based-observation/synop*  

====== Evaluate

. If the Global Broker discards all messages except one, makes it available on one of the two topics depending the WIS2 Node messages that arrived first.
. The MQTT client received one message
. Increments *wmo_wis2_gb_messages_subscribed_total* by 10 on both centre_id
. Increments *wmo_wis2_gb_messages_published_total* by 1 on centre_id from the WIS2Node that arrives first (io-wis2dev-11-test or io-wis2dev-12-test)
. If both statements are true, the test passes. Otherwise, the test fails.

===== Publishing a message using the centre_id from a different WIS2 Node

====== Purpose

The Global Broker service must ensure that any WIS2 Node is not publishing a message using a centre_id from another WIS2 Node 

====== Requirements

* The container https://hub.docker.com/r/golfvert/fakewis2node deployed on 10 tests system (*io-wis2dev-11-test* to *io-wis2dev-20-test*)
* Global Broker MQTT connection string to *io-wis2dev-11-test*
* MQTT Test Client

====== Steps

. Have WIS2Node  _io-wis2dev-11-test_ publish a valid message on topic Eg

====== Evaluate

. The Global Broker ignores (in fact the message will not be received at all) the message published. No metrics is incremented
. If the message is received by MQTT Client then the test fails.

===== Publishing messages from a WIS2 Node using valid topics (compliant with WIS2 Topic Hierarchy)

====== Purpose

The Global Broker service must forward messages when the topic is compliant with the WIS2 Topic Hierarchy 

====== Requirements

* The container https://hub.docker.com/r/golfvert/fakewis2node deployed on 5 tests system (*io-wis2dev-11-test* to *io-wis2dev-20-test*)
* Global Broker MQTT connection string to a WIS2 Nodes (*io-wis2dev-11-test*)
* MQTT Test Client

====== Steps

. Have WIS2Node *io-wis2dev-11-test* publish *valid* messages on *valid* topics hierarchy (one message per tested valid topic)

====== Evaluate

. The Global Broker forward all messages
. The MQTT client receives all messages
. Increments *wmo_wis2_gb_messages_subscribed_total* by 1 for each message 
. Increments *wmo_wis2_gb_messages_published_total* by 1 for each message
. If all above statements are true, the test passes. Otherwise, the test fails.

===== Publishing messages from a WIS2 Node using invalid topics (not compliant with WIS2 Topic Hierarchy)

====== Purpose

The Global Broker service must forward messages when the topic is compliant with the WIS2 Topic Hierarchy 

====== Requirements

* The container https://hub.docker.com/r/golfvert/fakewis2node deployed on 5 tests system (*io-wis2dev-11-test* to *io-wis2dev-20-test*)
*  Global Broker MQTT connection string to a WIS2 Nodes (*io-wis2dev-11-test*)
* MQTT Test Client

====== Steps

. Have WIS2 Node *io-wis2dev-11-test* publish 10 *valid* messages on 10 *different* and *invalid* topics

====== Evaluate

. The Global Broker discards all messages
. The MQTT client doesn't receive any message
. Increments *wmo_wis2_gb_messages_subscribed_total* by 10
. Increments *wmo_wis2_gb_messages_invalid_topic_total* by 10
. If all above statements are true, the test passes. Otherwise, the test fails.

===== Publishes messages from a WIS2 Node on a _valid_ topic without corresponding metadata

====== Purpose

The Global Broker service must check that the topic used to publish a message by a WIS2 Node is announcing the availability of data with corresponding metadata.

====== Requirements

* The container https://hub.docker.com/r/golfvert/fakewis2node deployed on 5 tests system (*io-wis2dev-11-test* to *io-wis2dev-20-test*)
* Global Broker MQTT connection string to a WIS2 Nodes (*io-wis2dev-11-test*)
* MQTT Test Client

====== Steps

. Have WIS2 Node *io-wis2dev-11-test* publish 10 *valid* messages on 10 *different* topics, and no metadata exists for any topic used.
. e.g Publish on *origin/a/wis2/_io-wis2dev-11-test_/core/data/weather/surface-based-observation/synop* and WIS2 Node *io-wis2dev-11-test* has not published a metadata record for the synop.


====== Evaluate

. The Global Broker discards all messages
. The MQTT client doesn't receive any message
. Increments *wmo_wis2_gb_messages_subscribed_total* by 10
. Increments *wmo_wis2_gb_messages_no_metadata_total* by 10
. If all above statements are true, the test passes. Otherwise, the test fails.

===== Verifying the compliance of a WIS2 Notification message

====== Purpose

The Global Broker service must verify the compliance of the WIS2 Notification Message with the agreed standard as specified in the Manual on WIS Vol. 2

====== Requirements

. The container https://hub.docker.com/r/golfvert/fakewis2node deployed on 5 tests system (*io-wis2dev-11-test* to *io-wis2dev-20-test*)
. Global Broker MQTT connection string to a WIS2 Nodes (*io-wis2dev-11-test*)
. MQTT Test Client

====== Steps

. Have WIS2 Node *io-wis2dev-11-test* publish 10 *invalid* messages on 10 *valid* topics
. All mandatory fields of the WIS2 Notification Messages must be tested 

====== Evaluate

. The Global Broker discards all messages
. The MQTT client doesn't receive any message
. Increments *wmo_wis2_gb_messages_subscribed_total* by 10
. Increments *wmo_wis2_gb_messages_invalid_messages_total* by 10
. If all above statements are true, the test passes. Otherwise, the test fails.


==== Performance tests

We must ensure that the Global Broker service performs properly under stress.  The following outlined tests will test the Global Broker service prior to transition of WIS2 to an operational state on January 1, 2025

===== Minimum number of WIS2 Nodes

====== Purpose

The Global Broker service should support a minimum of *200* WIS2 Nodes

====== Requirements

. The container https://hub.docker.com/r/golfvert/benchmarkwis2gb deployed on 5 tests system
. Global Broker subscribing to *200* WIS2 Nodes (*io-wis2dev-100-test* to *io-wis2dev-299-test*) 
. MQTT Test Client

====== Steps

. On each of the 200 WIS2 Nodes, publish 10 *valid* messages, on *valid* topic, without associated metadata, and with different *id* messages
. On the MQTT test client, subscribe to *origin/a/wis2/#*

====== Evaluate

. If on the MQTT test client, 10 messages for each of the 200 centre-id are received, the test passes. Otherwise, it fails.

===== Minimum number of subscribers

====== Purpose

The Global Broker service should support a minimum of *1000* subscribers.

====== Requirements

* Global Broker
* MQTTX CLI (https://mqttx.app/docs/cli) deployed on 5 tests systems

====== Steps

. Use MQTTX CLI _bench_ on each test system to simulate 200 clients by using `mqttx bench conn -c 200 -i 100` and the relevant connection information for the Global Broker being tested.

====== Evaluate

. If the output of the command on each test system is similar to:

```
mqttx bench conn -c 200 -i 100
❯  Starting connect benchmark, connections: 200, req interval: 100ms
✔  [200/200] - Connected
✔  Created 200 connections in 22.355s
```

with 200 connections created, on the 5 tests systems, this test is successful.

===== Minimum number of messages per second

====== Purpose

The Global Broker service should support processing of a minimum of *10000* messages per second.

====== Requirements

. The container https://hub.docker.com/r/golfvert/benchmarkwis2gb deployed on 5 tests system (different from above) 
. Global Broker subscribing to *200* WIS2 Nodes (*io-wis2dev-100-test* to *io-wis2dev-299-test*) 
. MQTTX CLI deployed on 5 tests systems.

====== Steps

. On each of the 200 WIS2 Nodes, publish X *valid* messages per second during Y seconds, on a *valid* topic, without associated metadata or data, and with different *id* messages
. Use MQTTX CLI _bench_ on each test VMs to simulate Z clients by using `mqttx bench sub -c Z -t origin/a/wis2/#` and the relevant connection information for the Global Broker being tested.

Typically with:

. With X = 5 messages per second on each of the 200 WIS2 Nodes, this will create 1000 messages per second
. With Z = 2 on each VM, this will create 10 subscriptions. 
. As every subscriber will get all messages will be equivalent to *10000* messages per second.

====== Evaluate

. Run the test for 30 seconds (Y=30), if MQTTS CLI output shows that 300000 are received, then the test is successful.
