[[global-cache-testing]]

=== Global Cache Service testing

==== Functional Tests

===== 1. MQTT Broker Connectivity

====== Purpose
An MQTT client must be able to connect to the local broker of the Global Cache on port 8883 using the MQTT protocol version 5 with TLS (i.e., mqtts protocol) and username/password authentication.

*Source:* Manual on WIS (WMO No. 1060), Vol II, clause 3.7.5.2: A Global Cache shall operate a message broker.

====== Requirements
* GC MQTT broker connection string
* MQTT Test Client

====== Steps

. Initialize the test MQTT client with the necessary parameters such as the MQTT protocol version 5, TLS security, and username/password for authentication (connection string).
. Attempt to connect the MQTT broker of the Global Cache using the connection string.

====== Evaluate

. Check if the connection is successful (rc code). If the connection is successful, the test passes. If the connection is not successful, the test fails.

===== 2. GC MQTT Broker Subscription

====== Purpose
A Global Cache must allow connected MQTT clients to subscribe to the ++cache/a/wis2/#++ topic using a provided connection string.

====== Requirements
* GC MQTT broker connection string
* MQTT Test Client

====== Steps

. Initialize a MQTT client with the necessary parameters such as the MQTT protocol version 5, TLS security, and username/password for authentication (connection string).
. Connect the MQTT client to the local broker of the Global Cache.
. Once the connection is successful, attempt to subscribe to the `cache/a/wis2/#` topic.

====== Evaluate

. Check if the subscription is successful. If the subscription is successful based on the returned rc code (SUBACK), the test passes. If the subscription is not successful, the test fails.
. Close the connection to the broker after the test.


===== 3. WIS2 Notification Message (WNM) Processing

====== Purpose
Test that the GC functions as expected under normal conditions. The Global Cache should process a valid incoming WNM, download the data at the provided canonical link, and publish a new WNM on the proper ++cache/++ topic using the proper message structure, and update the necessary GC metrics.

This test also evaluates the client data download requirement: An HTTP client (i.e., a Web browser) must be able to connect to the HTTP server of the Global Cache on port 443 using HTTP 1.1 with TLS but without any authentication and be able to resolve the URL provided in a data download link (a link object's `href` property where `rel=canonical`) from a notification message published by the Global Cache within the previous 24 hours; i.e., download a cached data item.

*Source:* Manual on WIS (WMO No. 1060), Vol II, clause 3.7.5.5: A Global Cache shall provide highly available access to copies of discovery metadata records and core data it stores; clause 3.7.5.6: A Global Cache shall retain a copy of the discovery metadata records and core data it stores for a duration compatible with the real-time or near-real-time schedule of the data and not less than 24 hours; clause 4.5.2: A Global Cache shall download core data and discovery metadata from [WIS2 Nodes] and other Global [Services] to provide for reliable, low-latency access to those resources via WIS; clause 4.5.6: Data and discovery metadata available for download from a Global Cache shall be accessible via a URL using at least one of the protocols specified [...].

*Source:* Manual on WIS (WMO No. 1060), Vol II, clause 3.7.5.4: Based on the notifications it receives, a Global Cache shall download and store a copy of discovery metadata records and core data from [WIS2 Nodes] and other Global [Services]; clause 3.7.5.7: A Global Cache shall publish notifications via its Message Broker about copies of the discovery metadata records and core data it makes available. A Global Cache shall use a standardized topic structure when publishing notifications; clause 4.5.2: A Global Cache shall download core data and discovery metadata from [WIS2 Nodes] and other Global [Services] to provide for reliable, low-latency access to those resources via WIS; clause 4.5.4: Based on received notifications, a Global Cache shall download core data from [WIS2 Nodes] or other Global [Services] and store them for a minimum duration of 24 hours; clause 4.5.5: Based on its received notifications, a Global Cache shall download discovery metadata records from [WIS2 Nodes] or other Global [Services] and store them for a minimum duration of 24 hours; clause 4.5.7: A Global Cache shall publish notifications to a Message Broker indicating  the availability of data and discovery metadata resources from the Global Cache and shall use the format and protocol specified [...].

*Source:* Guide to WIS (WMO No. 1061), Vol II, clause 2.7.4.1. [Global Cache] Technical considerations https://wmo-im.github.io/wis2-guide/guide/wis2-guide-DRAFT.html#_technical_considerations_2; clause 2.7.4.2. [Global Cache] Practices and procedures https://wmo-im.github.io/wis2-guide/guide/wis2-guide-DRAFT.html#_practices_and_procedures_2

====== Requirements
* Dev/test GB MQTT broker connection string
    ** MQTT user is able to read and write messages on the `origin/a/wis2/#` and `cache/a/wis2/#` topics.
* Dev/test GC is initiated and connected to the dev/test GB with subscriptions to the following topics:
    ** origin/a/wis2/+/data/#
    ** cache/a/wis2/+/data/#
    ** origin/a/wis2/+/metadata/#
    ** cache/a/wis2/+/metadata/#
* MQTT test client
    ** Client should connect to the dev/test GB MQTT broker using the provided connection string to control the input and monitor the output.
* GC metrics scraper
* Prepared WIS2 Notification Messages and associated data objects:
  ** A known number *https://github.com/wmo-im/wis2-notification-message[valid]* WNM's with:
    *** `properties.cache` set to true
    *** `properties.data_id` + `properties.pubtime` should be unique to each message. Ensuring a different data_id is best here.
  ** Accompanying data objects should be accessible via the canonical link provided in the WNM.
    *** The canonical link should be accessible per the core requirements and the data object hash should match the hash provided in the WNM if integrity properties are provided.

====== Steps

. Configure the MQTT test client to connect to the dev/test GB MQTT broker using the provided connection string.
. Publish a batch of Prepared WIS2 Notification Messages to the dev/test GB on following topics:
    ** Send 1 or more messages to origin/a/wis2/+/data/#
    ** Send 1 or more messages to cache/a/wis2/+/data/#
    ** Send 1 or more messages to origin/a/wis2/+/metadata/#
    ** Send 1 or more messages to cache/a/wis2/+/metadata/#
. The test MQTT client should store the messages received on the `cache/a/wis2/#` topic published by the GC and download the data objects from the canonical link provided in the messages using HTTP 1.1 with TLS.
    ** The original data object and the downloaded>>cached data objects can then be compared to ensure they are identical.

====== Evaluate
* WNM Messages
    ** The total number of cache notification messages published by the GC on the cache/a/wis2/# topic.
    ** All messages should be the same as the source WNM's except for:
        *** The canonical link (a link object's `href` property where `rel=canonical`), this should point to the GC's cached object.
        *** the unique identifier of the message (id)
        *** The topic, always on the `cache` channel. Note the incoming message may be unchanged if it was originally published on the `cache` channel.
* Data Objects
    ** The total number of data objects cached by the GC. This should match the number of cache notification messages published.
    ** The data objects cached by the GC should be identical to the source data objects.
        *** The diff or hashes of the data objects should be identical.
* GC Metrics
    ** `wmo_wis2_gc_download_total` (matches total messages)
    ** `wmo_wis2_gc_dataserver_status_flag` (set to 1 for each)
    ** `wmo_wis2_gc_dataserver_last_download_timestamp_seconds` (set for each and within expected time range)

===== 4. Cache False Directive
====== Purpose
Where a Global Cache receives a notification message with _properties.cache_ set to false, the Global Cache should publish a notification message where the data download link (a link object's `href` property where `rel=canonical`) refers to the source data server.

====== Requirements
* Dev/test GB MQTT broker connection string
    ** MQTT user is able to read and write messages on the `origin/a/wis2/#` and `cache/a/wis2/#` topics.
* Dev/test GC is initiated with subscription to the `cache/a/wis2/#` topic and `origin/a/wis2/#` topic of the dev/test GB.
* MQTT test client
    ** Client should connect to both the dev/test GB MQTT broker using the provided connection string to control the input and monitor the output.
* GC metrics scraper
* Prepared WIS2 Notification Messages and data objects:
  ** A known number *https://github.com/wmo-im/wis2-notification-message[valid]* WNM's with:
    *** `properties.cache` set to #false#
    *** `properties.data_id` + `properties.pubtime` should be unique to each message.
  ** Accompanying data objects are not required for this test.

====== Steps

. Configure the MQTT test client to connect to the dev/test GB MQTT broker using the provided connection string.
. Publish the prepared WIS2 Notification Messages to the dev/test GB the following topics:
    ** Send 1 or more messages to origin/a/wis2/+/data/#
    ** Send 1 or more messages to cache/a/wis2/+/data/#
    ** Send 1 or more messages to origin/a/wis2/+/metadata/#
    ** Send 1 or more messages to cache/a/wis2/+/metadata/#

====== Evaluate
* WNM Messages
    ** The total number of cache notification messages published by the GC on the `cache/a/wis2/#` topic
    ** all messages should be the same as the source WNM's except for:
        *** the unique identifier of the message (id)
        *** the topic (`cache/a/wis2/...`) (note the incoming message may be on the same `cache/#` topic if it is from another GC)
* GC Metrics
  ** `wmo_wis2_gc_download_total` (unchanged)
  ** `wmo_wis2_gc_dataserver_status_flag` (unchanged)
  ** `wmo_wis2_gc_dataserver_last_download_timestamp_seconds` (unchanged)
  ** `wmo_wis2_gc_no_cache_total` (+=1 for each WNM)

===== 5. Source Download Failure
====== Purpose
Where a Global Cache receives a valid WNM, but is unable to download a data item from the location specified in a notification message (i.e., the source data server), the `metric wmo_wis2_gc_dataserver_status_flag` for the source data server should be set to 0 (zero).

====== Requirements
* Dev/test GB MQTT broker connection string
    ** MQTT user is able to read and write messages on the `origin/a/wis2/#` and `cache/a/wis2/#` topics.
* Dev/test GC is initiated with subscription to the `cache/a/wis2/#` topic and `origin/a/wis2/#` topic of the dev/test GB.
* MQTT test client
    ** Client should connect the dev/test GB MQTT broker using the provided connection string to control the input and monitor the output.
* GC metrics scraper
* Prepared WIS2 Notification Messages and data objects
  ** A known number *https://github.com/wmo-im/wis2-notification-message[valid]* WNM's with:
    *** #invalid# data download links (a link object's `href` property where `rel=canonical`)
    *** `properties.data_id` + `properties.pubtime` should be unique to each message.
  ** Accompanying data objects are not required for this test.

====== Steps

. Configure the MQTT test client to connect to the dev/test MQTT broker using the provided connection string.
. Publish the prepared WNM's to the dev/test GB on one or more of the following topics:
    ** origin/a/wis2/+/data/#
    ** cache/a/wis2/+/data/#
    ** origin/a/wis2/+/metadata/#
    ** cache/a/wis2/+/metadata/#

====== Evaluate
* WNM Messages
    ** No messages should be published on the `cache/a/wis2/#` topic as received by the test MQTT client.
* Data Objects
    ** No data objects should be cached by the GC.
* GC Metrics
    ** `wmo_wis2_gc_download_total` (unchanged)
    ** `wmo_wis2_gc_dataserver_status_flag` (set to 0 for each)
    ** `wmo_wis2_gc_dataserver_last_download_timestamp_seconds` (unchanged)
    ** `wmo_wis2_gc_downloaded_errors_total` (+=1 for each WNM)

===== 6. Cache Override (Optional)
====== Purpose
Where a Global Cache determines that it is unable to cache a data item, the Global Cache should publish a notification message where the data download link (a link object's `href` property where `rel=canonical`) refers to the source data server, and the metric `wmo_wis2_gc_cache_override_total` is incremented by 1 (one).
Note that the trigger for this directive is implementation specific. The criteria must be known and enabled for the test
to be valid. Additionally, a given GC may decide to NOT implement this directive and thus this test is included as optional.

====== Requirements
* Dev/test GB MQTT broker connection string
    ** MQTT user is able to read and write messages on the `origin/a/wis2/#` and `cache/a/wis2/#` topics.
* Dev/test GC is initiated with subscription to the `cache/a/wis2/#` topic and `origin/a/wis2/#` topic of the dev/test GB.
* MQTT test client
    ** Client should connect to the dev/test GB MQTT broker using the provided connection string to control the input and monitor the output.
* GC metrics scraper
* Prepared WIS2 Notification Messages and data objects
  ** A known number *https://github.com/wmo-im/wis2-notification-message[valid]* WNM's with:
    *** `properties.cache` set to #true#
    *** `properties.data_id` + `properties.pubtime` should be unique to each message.
    *** #The known properties that trigger the cache override directive.#
  ** Accompanying data objects are not required for this test.

====== Steps

. Configure the MQTT test client to connect to the dev/test GB broker using the provided connection string.
. Publish the perpared WNM's to the dev/test GB on one or more of the following topics:
    ** origin/a/wis2/+/data/#
    ** cache/a/wis2/+/data/#
    ** origin/a/wis2/+/metadata/#
    ** cache/a/wis2/+/metadata/#

====== Evaluate
* Topic
    ** No messages should be published on the `cache/a/wis2/#` topic as received by the test MQTT client.
* WNM Messages
    ** No messages should be published on the `cache/a/wis2/#` topic as received by the test MQTT client.
* Data Objects
    ** No data objects should be cached by the GC.
* GC Metrics
    ** The following metrics are updated as expected per the prepared test data set:
        *** `wmo_wis2_gc_download_total` (unchanged)
        *** `wmo_wis2_gc_dataserver_status_flag` (unchanged)
        *** `wmo_wis2_gc_dataserver_last_download_timestamp_seconds` (unchanged)
        *** `wmo_wis2_gc_cache_override_total` (+=1 for each WNM)
        *** `wmo_wis2_gc_downloaded_errors_total` (unchanged)

===== 7. Data Integrity Check Failure (Recommended)
====== Purpose
A Global Cache should validate the integrity of the resources it caches and only accept data which matches the integrity value from the WIS Notification Message. If the WIS Notification Message does not contain an integrity value, a Global Cache should accept the data as valid. In this case a Global Cache _may_ add an integrity value to the message it republishes.

*Source:* Guide to WIS (WMO No. 1061), Vol II, clause 2.7.4.1. [Global Cache] Technical considerations https://wmo-im.github.io/wis2-guide/guide/wis2-guide-DRAFT.html#_technical_considerations_2; clause 2.7.4.2. [Global Cache] Practices and procedures https://wmo-im.github.io/wis2-guide/guide/wis2-guide-DRAFT.html#_practices_and_procedures_2
*Source:* https://github.com/wmo-im/wis2-notification-message/blob/main/standard/recommendations/core/REC_integrity.adoc

====== Requirements
* Dev/test GB MQTT broker connection string
    ** MQTT user is able to read and write messages on the `origin/a/wis2/#` and `cache/a/wis2/#` topics.
* Dev/test GC is initiated with subscription to the `cache/a/wis2/#` topic and `origin/a/wis2/#` topic of the dev/test GB.
* MQTT test client
    ** Client should connect to the dev/test GB MQTT broker using the provided connection string to control the input and monitor the output.
* GC metrics scraper
* Prepared WIS2 Notification Messages and data objects
  ** A known number *https://github.com/wmo-im/wis2-notification-message[valid]* WNM's with:
    *** #invalid# data integrity value (accessed via `properties.integrity.value` and the method specified in `properties.integrity.method`)
    *** `properties.data_id` + `properties.pubtime` should be unique to each message.
  ** Accompanying data objects that are accessible via the canonical link provided in the WNM

====== Steps
. Publish the prepared WNM's to the dev/test GB on one or more of the following topics:
    ** origin/a/wis2/+/data/#
    ** cache/a/wis2/+/data/#
    ** origin/a/wis2/+/metadata/#
    ** cache/a/wis2/+/metadata/#

====== Evaluate
* WNM Messages
    ** No messages should be published on the `cache/a/wis2/#` topic as received by the test MQTT client.
* Data Objects
    ** No data objects should be cached by the GC.
* GC Metrics
    ** `wmo_wis2_gc_download_total` (unchanged)
    ** `wmo_wis2_gc_dataserver_status_flag` (set to 0 for each)
    ** `wmo_wis2_gc_dataserver_last_download_timestamp_seconds` (unchanged)
    ** `wmo_wis2_gc_downloaded_errors_total` (+=1 for each WNM)
    ** `wmo_wis2_gc_integrity_failed_total` (+=1 for each WNM)

===== 8. WIS2 Notification Message Deduplication
====== Purpose
A Global Cache must ensure that only one instance of a notification message with a given unique identifier (id) is successfully processed.

*Source:* Manual on WIS (WMO No. 1060), Vol II, clause 3.7.5.3: A Global Cache shall subscribe to notifications about the availability of discovery metadata records and core data for real-time or near-real-time exchange. Duplicate notifications are discarded.

====== Requirements
* Dev/test GB MQTT broker connection string
    ** MQTT user is able to read and write messages on the `origin/a/wis2/#` and `cache/a/wis2/#` topics.
* Dev/test GC is initiated with subscription to the `cache/a/wis2/#` topic and `origin/a/wis2/#` topic of the dev/test GB.
* MQTT test client
    ** Client should connect to the dev/test GB MQTT broker using the provided connection string to control the input and monitor the output.
* GC metrics scraper
* Prepared WIS2 Notification Messages and data objects
  ** A known number *https://github.com/wmo-im/wis2-notification-message[valid]* WNM's where:
    *** `properties.data_id` + `properties.pubtime` are #NOT# unique to each message, but shared by 2 or more messages.
  ** Accompanying data objects that are accessible via the canonical link provided in the WNM,

====== Steps
. Publish the prepared WNM's to the dev/test GB on one or more of the following topics:
    ** origin/a/wis2/+/data/#
    ** cache/a/wis2/+/data/#
    ** origin/a/wis2/+/metadata/#
    ** cache/a/wis2/+/metadata/#

====== Evaluate
* WNM Messages
    ** Only one message should be published by the GC on the `cache/a/wis2/#` topic per unique identifier which is defined as `properties.data_id` + `properties.pubtime`.
        *** Note that due to the update directive related to 8.2, prepared messages should use unique data_id's to ensure uniqueness.
* Data Objects
    ** Only one data object should be cached per unique identifier which is defined as `properties.data_id` + `properties.pubtime`.
* GC Metrics
    ** `wmo_wis2_gc_download_total` (+=1 for each unique identifier)
    ** `wmo_wis2_gc_dataserver_status_flag` (set to 1 for each unique identifier)
    ** `wmo_wis2_gc_dataserver_last_download_timestamp_seconds` (set to current for each unique identifier)
    ** `wmo_wis2_gc_downloaded_errors_total` (unchanged)
    ** `wmo_wis2_gc_integrity_failed_total` (unchanged)


===== 8.1. WIS2 Notification Message Deduplication (Alternative 1)

====== Purpose
Where a Global Cache fails to process a notification message relating to a given unique data object (`properties.data_id` + `properties.pubtime`), a Global Cache should successfully process a valid, subsequently received notification message with the same unique data identifier.

*Source:* Manual on WIS (WMO No. 1060), Vol II, clause 3.7.5.3: A Global Cache shall subscribe to notifications about the availability of discovery metadata records and core data for real-time or near-real-time exchange. Duplicate notifications are discarded.

====== Requirements
* Dev/test GB MQTT broker connection string
    ** MQTT user is able to read and write messages on the `origin/a/wis2/#` and `cache/a/wis2/#` topics.
* Dev/test GC is initiated with subscription to the `cache/a/wis2/#` topic and `origin/a/wis2/#` topic of the dev/test GB.
* MQTT test client
    ** Client should connect to the dev/test GB MQTT broker using the provided connection string to control the input and monitor the output.
* GC metrics scraper
* Prepared WIS2 Notification Messages and data objects
  ** A known number *https://github.com/wmo-im/wis2-notification-message[valid]* WNM's where:
    *** `properties.data_id` + `properties.pubtime` are #NOT# unique to each message, but shared by 2 or more messages.
    *** This defines a unique identifier message set.
    *** For each unique identifier message set, the first published message should be invalid, or the data object inaccessible, and the second message/data object should be valid.
  ** Accompanying data objects that are accessible (or not) via the canonical link provided in the WNM.

====== Steps
. Publish the prepared WNM's to the dev/test GB such that the invalid WNM for each unique data identifier is published first. One or more of the following topics can be used:
    ** origin/a/wis2/+/data/#
    ** cache/a/wis2/+/data/#
    ** origin/a/wis2/+/metadata/#
    ** cache/a/wis2/+/metadata/#

====== Evaluate
* WNM Messages
    ** Only one message should be received on the `cache/a/wis2/#` topic per unique identifier which is defined as `properties.data_id` + `properties.pubtime`.
* Data Objects
    ** Only one data object should be cached per unique identifier which is defined as `properties.data_id` + `properties.pubtime`.
* GC Metrics
    ** `wmo_wis2_gc_download_total` (+=1 for each unique identifier)
    ** `wmo_wis2_gc_dataserver_status_flag` (set to 1 for each unique identifier)
    ** `wmo_wis2_gc_dataserver_last_download_timestamp_seconds` (set to current for each unique identifier)
    ** `wmo_wis2_gc_downloaded_errors_total` (+=1 for each unique identifier WNM message set)
    ** `wmo_wis2_gc_integrity_failed_total` (unchanged)


===== 8.2. WIS2 Notification Message Deduplication (Alternative 2)
====== Purpose
Related to the two previous tests, a GC should not process and cache a data item if it has already processed and cached a data item with the same `properties.data_id` and a `properties.pubtime` that is equal to or less than the `properties.pubtime` of the new data item. This test is an extension of the previous tests and can be conducted in conjunction with them.

====== Requirements
See above.

====== Steps
. Publish the prepared WNM's to the dev/test GB such for each unique identifier message set, the first published message has a pubtime that is #greater than or equal to# the subsequent message/s. One or more of the following topics can be used:
    ** origin/a/wis2/+/data/#
    ** cache/a/wis2/+/data/#
    ** origin/a/wis2/+/metadata/#
    ** cache/a/wis2/+/metadata/#

====== Evaluate
* WNM Messages
    ** For each message set with a shared data_id, each message should be processed by the GC and received on the `cache/a/wis2/#` topic assuming that the `properties.pubtime` as been correctly set (decreasing or equal) for each message sent in chronological order.
* Data Objects
    ** For each message set with a shared data_id, each data object should be cached by the GC and assuming that the `properties.pubtime` as been correctly set (decreasing or equal) for each message sent in chronological order.
* GC Metrics
    ** `wmo_wis2_gc_download_total` (+=1 for each set of messages sharing the same data_id)
    ** `wmo_wis2_gc_dataserver_status_flag` (set to 1)
    ** `wmo_wis2_gc_dataserver_last_download_timestamp_seconds` (set to current)
    ** `wmo_wis2_gc_downloaded_errors_total` (unchanged)
    ** `wmo_wis2_gc_integrity_failed_total` (unchanged)

===== 9. Data Update

====== Purpose
A Global Cache should treat notification messages with the same data item identifier (`properties.data_id`), but different publication times (`properties.pubtime`) as unique data items. Data items with the same `properties.data_id` but a greater/later publication time AND a #update# link (links['rel']='update'), should be processed (see test Notification processing). Data items with the same `properties.data_id` but earlier or identical publication times should be ignored (see deduplication test 8).

*Source:* Guide to WIS (WMO No. 1061), Vol II, clause 2.7.4.2. [Global Cache] Practices and procedures: “Verify if the message points to new or updated data by comparing the pubtime value of the notification message with the list of data_ids”. https://wmo-im.github.io/wis2-guide/guide/wis2-guide-DRAFT.html#_practices_and_procedures_2

====== Requirements
* Dev/test GB MQTT broker connection string
    ** MQTT user is able to read and write messages on the `origin/a/wis2/#` and `cache/a/wis2/#` topics.
* Dev/test GC is initiated with subscription to the `cache/a/wis2/#` topic and `origin/a/wis2/#` topic of the dev/test GB.
* MQTT test client
    ** Client should connect to the dev/test GB MQTT broker using the provided connection string to control the input and monitor the output.
* GC metrics scraper
* Prepared WIS2 Notification Messages and data objects
  ** A known number *https://github.com/wmo-im/wis2-notification-message[valid]* WNM's where:
    *** `properties.data_id` + `properties.pubtime` are unique to each message, but the properties.data_id is shared by 2 or more messages and the pubtimes are different.
    *** Ensure that for a given shared data_id, the message with the latest pubtime has link with `rel=update`.
    *** This defines a unique identifier message set.
  ** Accompanying data objects that are accessible via the canonical link provided in the WNM.

====== Steps
. Publish the prepared WNM's to the dev/test GB such for each unique identifier message set, the first published message has a pubtime that is less than the subsequent message/s and subsequent messages have a valid update link. One or more of the following topics can be used:
    ** origin/a/wis2/+/data/#
    ** cache/a/wis2/+/data/#
    ** origin/a/wis2/+/metadata/#
    ** cache/a/wis2/+/metadata/#

====== Evaluate
* WNM Messages
    ** For each message set with a shared data_id, each message should be processed by the GC and received on the `cache/a/wis2/#` topic assuming that the `properties.pubtime` as been correctly set (increasing) for each message sent in chronological order.
* Data Objects
    ** For each message set with a shared data_id, each data object should be cached by the GC and assuming that the `properties.pubtime` as been correctly set (increasing) for each message sent in chronological order.
* GC Metrics
    ** `wmo_wis2_gc_download_total` (+=1 for each message)
    ** `wmo_wis2_gc_dataserver_status_flag` (set to 1)
    ** `wmo_wis2_gc_dataserver_last_download_timestamp_seconds` (set to current)
    ** `wmo_wis2_gc_downloaded_errors_total` (unchanged)
    ** `wmo_wis2_gc_integrity_failed_total` (unchanged)

==== Performance tests

===== WIS2 Notification Processing Rate

====== Purpose
A Global Cache shall be able to successfully process, on average, 2000 unique WNM's per minute with an average message size of 75kb. This test represents the upper end of the current WNM volume. This test is a measured performance test similar to test 3. WNM Processing except that a large batch of messages is used, and the time taken to process the messages is measured. The noted WNM's/minute rate can be used as a performance indicator for the GC being tested.

====== Requirements
* Dev/test GB MQTT broker connection string
    ** MQTT user is able to read and write messages on the `origin/a/wis2/#` and `cache/a/wis2/#` topics.
* Dev/test GC is initiated and connected to the dev/test GB with subscriptions to the following topics:
    ** origin/a/wis2/+/data/#
    ** cache/a/wis2/+/data/#
    ** origin/a/wis2/+/metadata/#
    ** cache/a/wis2/+/metadata/#
* MQTT test client
    ** Client should connect to the dev/test GB MQTT broker using the provided connection string to control the input and monitor the output.
* GC metrics scraper
* Prepared WIS2 Notification Messages and associated data objects:
  ** A known number *https://github.com/wmo-im/wis2-notification-message[valid]* WNM's with:
    *** `properties.cache` set to true
    *** `properties.data_id` + `properties.pubtime` should be unique to each message. The ensure consistency, data_id alone should be used to determine uniqueness.
  ** Accompanying data objects should be accessible via the canonical link provided in the WNM.
    *** The canonical link should be accessible per the core requirements and the data object hash should match the hash provided in the WNM if integrity properties are provided.
    *** Average message size should be 75kb.

====== Steps
. Start the timer, and publish the batch of 2000 prepared WNM's to the dev/test GB on following topics:
    ** origin/a/wis2/+/data/#
    ** cache/a/wis2/+/data/#
    ** origin/a/wis2/+/metadata/#
    ** cache/a/wis2/+/metadata/#
. The test MQTT client should count the messages received on the `cache/a/wis2/#` topic that are published by the GC, but should not download the data objects.
. Stop the timer when the MQTT client has received all expected messages (2000). A timeout can be set to allow the test to run as long as needed within a reasonable window.

====== Evaluate
* WNM Messages
    ** The total number of cache notification messages published by the GC on the cache/a/wis2/# topic should match what was published (2000).
* GC Metrics
    ** `wmo_wis2_gc_download_total` matches total expected messages.

* The time taken to process the messages should not exceed 60 seconds (plus time taken to publish the WNM's) in order to pass the test.
    ** The results can be used as a baseline for the GC's performance.

===== Concurrent client downloads

====== Purpose
A Global Cache should support a minimum of 1000 simultaneous downloads.

*Source:* Manual on WIS (WMO No. 1060), Vol II, clause 3.7.5.5: A Global Cache shall provide highly available access to copies of discovery metadata records and core data it stores; clause 4.5.1: A Global Cache shall operate a highly available storage and download service; clause 4.5.2: A Global Cache shall download core data and discovery metadata from [WIS2 Nodes] and other Global [Services] to provide for reliable, low-latency access to those resources via WIS.
*Source:* Guide to WIS (WMO No. 1061), Vol II, clause 2.7.2.2. Service levels, performance indicators and fair-usage policies: https://wmo-im.github.io/wis2-guide/guide/wis2-guide-DRAFT.html#_procedure_for_registration_of_a_new_global_service

====== Requirements
* Dev/test GB MQTT broker connection string
    ** MQTT user is able to read and write messages on the `origin/a/wis2/#` and `cache/a/wis2/#` topics.
* Dev/test GC is initiated and connected to the dev/test GB with subscriptions to the following topics:
    ** origin/a/wis2/+/data/#
    ** cache/a/wis2/+/data/#
    ** origin/a/wis2/+/metadata/#
    ** cache/a/wis2/+/metadata/#
* MQTT test client
    ** Client should connect to the dev/test GB MQTT broker using the provided connection string to control the input and monitor the output.
* Prepared WIS2 Notification Messages and associated data objects:
  ** A known number (5) *https://github.com/wmo-im/wis2-notification-message[valid]* WNM's with:
    *** `properties.cache` set to true
    *** `properties.data_id` + `properties.pubtime` should be unique to each message. Ensuring a different data_id is best here.
  ** Valid data objects to be cached
    *** A larger than average data object should be generated/used in order to ensure that the clients downloading the data object concurrently do not finish before the test is complete. A 500MB data object is recommended.
* Jmeter, Locust, or similar tool to manage the concurrent downloads.

====== Steps
. Publish the prepared WNM's one at a time to the dev/test GB on one of the following topics:
    ** origin/a/wis2/+/data/#
    ** cache/a/wis2/+/data/#
    ** origin/a/wis2/+/metadata/#
    ** cache/a/wis2/+/metadata/#

For each WNM:
. Once the _cache_ notification message is received by the test MQTT client (from the dev/test GC), the test client should start 1000 concurrent downloads of the data object/s from the canonical link provided in the _cache_ WNM.
. The test client should record the number of successful downloads and the time taken to complete each download.

====== Evaluate
The test is considered successful if the following conditions are met:
* The total number of successful downloads is 1000.
* While the download time can be used to establish a baseline, it is highly dependent on the network and server conditions of the test environment and should not be used as a pass/fail criteria.


==== Implicit tests
These are tests that are to be verified by the individual implementations as they represent critical requirements but would be difficult to test in a generic way.

===== Valid TLS/SSL certificate
* A Global Cache must have a valid TLS/SSL certificate to ensure secure communication with other WIS2 components.

===== Available Storage Space
* A Global Cache shall be able to store at least 100GB of Core data items.

*Source:* Guide to WIS (WMO No. 1061), Vol II, clause 2.7.2.2. Service levels, performance indicators and fair-usage policies: “A Global Cache should support a minimum of 100 GB of data in the cache” https://wmo-im.github.io/wis2-guide/guide/wis2-guide-DRAFT.html#_procedure_for_registration_of_a_new_global_service

