[[wis2-to-gts-gateway-testing]]

=== WIS2-to-GTS Gateway testing

Each WIS2-to-GTS Gateway instance will be tested using the methodology outlined below. The Gateway instances:
* Shall not publish bulletins onto the GTS during the tests (the Gateways should compile the GTS bulletins - but not send them).
* Do not need to be deployed into the `wis2dev.io` test environment (there are no side effects from running these tests because GTS bulletins are not published).

The performance tests utilise the live feed of WIS2 Notification Messages from the `de-dwd-gts-to-wis2` Gateway. This feed contains all the published GTS traffic so is guarenteed to be busy. Other tests use _fake_ WIS2 Nodes configured to provide notification messages with specific characteristics.

Both WIS2-to-GTS Gateways are tested in parallel. The tests are run manually. The results require manual inspection of the metrics and outputs. Comparing differences between Gateway instances is useful to spot errors.

As (most) of the traffic distributed by `de-dwd-gts-to-wis2` is about observations and arrives at the top of the hour, each hour, the following schedule is recommended:
* 00 min : Start and quick assessment on the readiness of both Gateways
* 10 min : Run the 11 functional test (it should take a bit more than 30' in total)
* 50 min : Start the 30-min "real" traffic test
* 95 min : End of the 30-min tests and metrics gathering
* 100 min : Run the heavy-load test (10000 messages over 5 minutes)

The schedule above ensures that the busy GTS traffic period coincides with the 30-min test.

**There are 11 functional tests** - two of which have variants:

. Inline data (data embedded within the WNM) retrieved OK
. Failure to retrieve data from URL
. Failure to retrieve inline data, success to retrieve data from URL
. Failure to retrieve inline data, failure to retrieve data from URL
. Bad “integrity”: (A) for inline data, (B) for data retrieved from URL
. WNM deduplication Alt 1: when the first WNM for a given data-object fails to be processed, a subsequent WNM should be processed OK
. WNM deduplication Alt 2: when a WNM for a given data-object is successfully processed, a WNM for that data-object but earlier (or same) pubtime should not be processed
. Updated data-objects trigger CORRECTION: (A) using URL, (B) Using inline data
. Updated data-objects trigger CORRECTION with correct CCx sequence number and ignore updates that arrive out of sequence
. Late arrival of data-objects for same bulletin trigger RETARD
. GTS property syntax validation failure

These functional tests do not evaluate functionality of Message Switch as these components are already known to function correctly in operations. The Gateways should compile the GTS bulletins but not send them to GTS.

**There are 2 performance tests**:

. Heavy-load test
. 30-minutes test

[[wis2-to-gts-gateway-setup-teardown]]

==== Preparation

===== Setup

Before running the tests, ensure the following setup steps are completed:

====== Disconnect the Gateway from the production environment.

Ensure that the Gateway is not connected to the production environment during the testing session. This ensures that all testing is completed in a controlled environment.

. Remove other subscriptions to prod GB's.
    - Ensure that the Gateway is not subscribed to any other Global Broker except the dev/test Global Broker.

====== Connect the Gateway to the dev/test environment.

Ensure that the Gateway is connected to the dev/test environment during the testing session. This is to allow the test messages to be propagated to the Gateway for testing.

. Gateway Subscription to the dev/test Global Broker.
    * Ensure the Gateway is subscribed to the dev/test Global Broker (`gb.wis2dev.io`).
        -  the connection string to be used is: `mqtts://everyone-dev:everyone-dev@gb.wis2dev.io:8883`
    * The Gateway should be subscribed to the following topics:
        - `origin/a/wis2/+/data/#`
        - `cache/a/wis2/+/data/#`

===== Teardown

To teardown the configuration after the testing session, simply reverse the setup steps:

- Unsubscribe the Gateway from the dev/test Global Broker.
- Reset the metrics so that dev and prod metrics are not mixed.
- Reconnect the Gateway Cache to the production environment by re-subscribing to the production Global Brokers.

[[wis2-to-gts-gateway-tests]]

==== Functional tests:

All functional tests use Fake WIS2 Node with a variety of configurations.

For all tests when needed: TTAAii = `EFGH10` CCCC = `ABCD`.

===== Inline data (data embedded within the WNM) retrieved OK
* Provide a WNMs with inline data
* ... 10 with whitelisted GTS properties << these should be processed correctly
* ... 10 with non-whitelisted GTS properties << these should be ignored
* ... 10 without GTS properties << these should be ignored
* Gateways should successfully process the 10 WNMs with whitelisted GTS properties, and ignore the others

===== Failure to retrieve data from URL
* Provide 10 WNMs with 
* ... whitelisted GTS properties
* ... no inline data
* ... bad (unresolvable) URL for the canonical data << this data cannot be retrieved
* Gateways should throw errors; no data “published”

===== Failure to retrieve inline data, success to retrieve data from URL
* Provide 10 WNMs with 
* ... whitelisted GTS properties
* ... inline data, but bad `size` attribute << this should force the Gateway to throw an error and then try to retrieve data via the remote URL
* ... No `properties.integrity` in WNM. So, size is the only option to verify the embedded is not correct.
* ... resolvable URL for the canonical data << these data should be processed
* Gateways should trigger error (for inline retrieval); data “published” (for URL retrieval)

===== Failure to retrieve inline data, failure to retrieve data from URL
* Provide 10 WNMs with 
* ... whitelisted GTS properties
* ... inline data, but bad `size` attribute << this should force the Gateway to throw an error and then try to retrieve data via the remote URL
* ... bad (unresolvable) URL for the canonical data << this should force the Gateway to throw an error; this data cannot be retrieved
* Gateways should trigger error (for inline retrieval and for URL retrieval); no data “published”

===== Bad “integrity” for inline data
* Provide 10 WNMs with 
* ... whitelisted GTS properties
* ... inline data
* ... resolvable URL for the canonical data
* ... bad `method` and/or `value` for `properties.integrity` << this should force the Gateway to throw an error when trying to process _both_ inline data and data retrieved from URL
* Gateways should trigger error (for validation of inline data and for validation of data retrieved from URL); no data “published”

===== Bad “integrity” for data retrieved from URL
* Provide 10 WNMs with 
* ... whitelisted GTS properties
* ... no inline data
* ... resolvable URL for the canonical data
* ... bad `method` and/or `value` for `properties.integrity` << this should force the Gateway to throw an error when trying to process data retrieved from URL
* Gateways should trigger error (for validation of data retrieved from URL); no data “published”

===== WNM deduplication Alt 1: when the first WNM for a given data-object fails to be processed, a subsequent WNM should be processed OK
* Provide 10 pairs of WNMs with
* ... whitelisted GTS properties
* ... _may_ include inline data
* ... each pair of WNMs must have same data-id and pubtime
* ... first WNM of pair: bad `method` and/or `value` for `properties.integrity` << this should force the Gateway to throw an error when trying to process data retrieved from URL
* ... second WNM of pair: good `method` and `value` for `properties.integrity` << this should be processed OK
* Gateways should throw an error for first WNM in the pair, but successfully process the second WNM in the pair

===== WNM deduplication Alt 2: when a WNM for a given data-object is successfully processed, a WNM for that data-object but earlier (or same) pubtime should not be processed
* Provide 10 pairs of WNMs with
* ... whitelisted GTS properties
* ... _may_ include inline data
* ... each pair of WNMs must have same `data-id` (and otherwise be “good”/valid messages)
* ... first WNM of pair: `pubtime` = {time} << this should be processed OK
* ... second WNM of pair: `pubtime` = {time – `x` seconds} << `x` could be 1 to 60 seconds (or longer), this message should be ignored 
* Gateways successfully process the first WNM in the pair and ignore the second WNM in the pair

===== Updated data-objects trigger CORRECTION – Using URL
* Provide 5 pairs of WNMs with 
* ... whitelisted GTS properties
* ... does not include inline data
* ... each pair of WNMs must have same `data-id` (and otherwise be “good”/valid messages)
* ... first WNM of pair: `pubtime` = {time} << this should be processed OK
* ... wait (long enough for the bulletin compilation window to expire – thereby avoiding the Gateway compiling both reports into the same bulletin)
* ... second WNM of pair: `pubtime` = {time + `x`}, data URL link has `rel=update` << this should be processed OK
* Gateways should process both WNMs in each pair – the second WNM should result in a bulletin being flagged as a CORRECTION (CCx)

Note: Pairs of messages may be interleaved – i.e., send all 5 of the first of the pairs, wait, then send all 5 of the second of the pairs.

===== Updated data-objects trigger CORRECTION – Using inline data
* Provide 5 pairs of WNMs with 
* ... whitelisted GTS properties
* ... include inline data
* ... each pair of WNMs must have same `data-id` (and otherwise be “good”/valid messages)
* ... first WNM of pair: `pubtime` = {time} << this should be processed OK
* ... wait (long enough for the bulletin compilation window to expire – thereby avoiding the Gateway compiling both reports into the same bulletin)
* ... second WNM of pair: `pubtime` = {time + `x`}, data URL link has `rel=update` << this should be processed OK
* Gateways should process both WNMs in each pair – the second WNM should result in a bulletin being flagged as a CORRECTION (CCx)
* The `links.href` is invalid so only inline data can be used

Note: Pairs of messages may be interleaved – i.e., send all 5 of the first of the pairs, wait, then send all 5 of the second of the pairs.

===== Updated data-objects trigger CORRECTION with correct CCx sequence number and ignore updates that arrive out of sequence
* Provide 5 quads of WNMs (i.e., groups of 4 messages) with 
* ... whitelisted GTS properties
* ... _may_ include inline data
* ... each quad of WNMs must have same `data-id` (and otherwise be “good”/valid messages)
* ... first WNM of quad: `pubtime` = {time} << this should be processed OK
* ... wait (long enough for the bulletin compilation window to expire – thereby avoiding the Gateway compiling both reports into the same bulletin)
* ... second WNM of quad: `pubtime` = {time + `x`}, data URL link has `rel=update` << this should be processed OK and trigger a bulletin with BBB = `CCA`
* ... wait
* ... third WNM of quad: `pubtime` = {time + `y`}, data URL link has `rel=update` << (where time `y` exceeds `x`, i.e., it is published later) this should be processed OK and trigger a bulletin with BBB = `CCB`
* ... wait
* ... fourth WNM of quad: `pubtime` = {time + `x`}, data URL link has `rel=update` << this WNM should be ignored
* Gateways should process the first 3 WNMs in each quad – creating 3 bulletins, the first with no BBB, the second with BBB = `CCA`, the third with BBB = `CCB`; the fourth WNM should be ignored   

Note: Quads of messages may be interleaved

===== Late arrival of data-objects for same bulletin trigger RETARD
* Provide 5 pairs of WNMs with 
* ... whitelisted GTS properties
* ... _may_ include inline data
* ... each pair of WNMs must have same GTS properties (and otherwise be “good”/valid messages) << this means they should be compiled into the same bulletin by the Gateway
* ... first WNM of pair: `data-id` = {A}, `pubtime` = {time} << this should be processed OK
* ... wait (long enough for the bulletin compilation window to expire – thereby avoiding the Gateway compiling both reports into the same bulletin)
* ... second WNM of pair: `data-id` = {B}, `pubtime` = {time + `x`} << this should be processed OK
* Gateways should process both WNMs in each pair – the second WNM should result in a bulletin being flagged as a RETARD (RRx)

===== GTS property syntax validation failure
* Provide a WNMs with
* ... 10 with whitelisted GTS properties << these should be processed correctly
* ... 10 with non-whitelisted GTS properties << these should be ignored
* ... 10 without GTS properties << these should be ignored
* ... 10 with bad GTS properties, i.e., incorrect syntax for TTAAii (6 chars, sequence of 4 alphabetic characters followed by 2 numeric characters) and/or CCCC (sequence of 4 alphabetic characters) << this should trigger the Gateway to throw errors
* Gateways should successfully process the 10 WNMs with whitelisted GTS properties, ignore the WNMs with valid but not whitelisted GTS properties, ignore the WNMs without GTS properties, and throw errors for the WNMs with invalid GTS properties 


==== Performance tests:

===== Pre-requisites
* Assessment of live GTS traffic gives the top-40 TTAAii/CCCC headers with the most traffic: "TOP40".

===== Heavy-load test 
* Use Fake WIS2 Node
* 2000 messages / min for 5-minutes
* GTS properties (TTAAii CCCC) included in the generated messages; same TTAAii CCCC for all messages is OK 
* Ensure that TTAAii CCCC is whitelisted
* TTAAii = `EFGH10` CCCC = `ABCD`
* The WIS2-to-GTS gateway instances should be able to sustain this message throughput.

===== 30-minutes test
* GTS-to-WIS2 gateway feed sustained for 30-minutes (recommend using `de-dwd-gts-to-wis2` instance)
* The TOP40 TTAAii/CCCC are whitelisted.
* The list of whitelisted TTAAii/CCCC is identical between the two gateways.
* Metrics from each WIS2-to-GTS gateway instance are compared (they should be identical).



