ssh rocky@test-node-1.wis2dev.io "docker stop wis2nodebench2; docker stop wis2nodebench1; docker rm wis2nodebench2; docker rm wis2nodebench1"
ssh rocky@test-node-2.wis2dev.io "docker stop wis2nodebench2; docker stop wis2nodebench1; docker rm wis2nodebench2; docker rm wis2nodebench1"
ssh rocky@test-node-3.wis2dev.io "docker stop wis2nodebench2; docker stop wis2nodebench1; docker rm wis2nodebench2; docker rm wis2nodebench1"
ssh rocky@test-node-4.wis2dev.io "docker stop wis2nodebench2; docker stop wis2nodebench1; docker rm wis2nodebench2; docker rm wis2nodebench1"
ssh rocky@test-node-5.wis2dev.io "docker stop wis2nodebench2; docker stop wis2nodebench1; docker rm wis2nodebench2; docker rm wis2nodebench1"
ssh rocky@test-node-6.wis2dev.io "docker stop wis2nodebench2; docker stop wis2nodebench1; docker rm wis2nodebench2; docker rm wis2nodebench1"
ssh rocky@test-node-7.wis2dev.io "docker stop wis2nodebench2; docker stop wis2nodebench1; docker rm wis2nodebench2; docker rm wis2nodebench1"
ssh rocky@test-node-8.wis2dev.io "docker stop wis2nodebench2; docker stop wis2nodebench1; docker rm wis2nodebench2; docker rm wis2nodebench1"
ssh rocky@test-node-9.wis2dev.io "docker stop wis2nodebench2; docker stop wis2nodebench1; docker rm wis2nodebench2; docker rm wis2nodebench1"
ssh rocky@test-node-10.wis2dev.io "docker stop wis2nodebench2; docker stop wis2nodebench1; docker rm wis2nodebench2; docker rm wis2nodebench1"
ssh rocky@test-node-1.wis2dev.io "docker stop mosquitto; docker rm mosquitto"
ssh rocky@test-node-2.wis2dev.io "docker stop mosquitto; docker rm mosquitto"
ssh rocky@test-node-3.wis2dev.io "docker stop mosquitto; docker rm mosquitto"
ssh rocky@test-node-4.wis2dev.io "docker stop mosquitto; docker rm mosquitto"
ssh rocky@test-node-5.wis2dev.io "docker stop mosquitto; docker rm mosquitto"
ssh rocky@test-node-6.wis2dev.io "docker stop mosquitto; docker rm mosquitto"
ssh rocky@test-node-7.wis2dev.io "docker stop mosquitto; docker rm mosquitto"
ssh rocky@test-node-8.wis2dev.io "docker stop mosquitto; docker rm mosquitto"
ssh rocky@test-node-9.wis2dev.io "docker stop mosquitto; docker rm mosquitto"
ssh rocky@test-node-10.wis2dev.io "docker stop mosquitto; docker rm mosquitto"
ssh rocky@test-node-1.wis2dev.io "docker stop wis2node; docker rm wis2node"
ssh rocky@test-node-2.wis2dev.io "docker stop wis2node; docker rm wis2node"
ssh rocky@test-node-3.wis2dev.io "docker stop wis2node; docker rm wis2node"
ssh rocky@test-node-4.wis2dev.io "docker stop wis2node; docker rm wis2node"
ssh rocky@test-node-5.wis2dev.io "docker stop wis2node; docker rm wis2node"
ssh rocky@test-node-6.wis2dev.io "docker stop wis2node; docker rm wis2node"
ssh rocky@test-node-7.wis2dev.io "docker stop wis2node; docker rm wis2node"
ssh rocky@test-node-8.wis2dev.io "docker stop wis2node; docker rm wis2node"
ssh rocky@test-node-9.wis2dev.io "docker stop wis2node; docker rm wis2node"
ssh rocky@test-node-10.wis2dev.io "docker stop wis2node; docker rm wis2node"
